#!/usr/bin/env python3
"""
IV Wellness — Myers Cocktail "The Ultimate Recharge IV" nurture sequence
(28-day, linear).

Trigger swaps (set in GHL UI before activating; this script only seeds tags):
  WF-01 master: trigger source = Facebook Lead Ads form submission for the
    Myers Cocktail campaign. The form-fill action should add the
    `myers-lead` tag, which is what this script registers as the workflow tag.
  WF-02 RESET keyword recovery: trigger = Inbound SMS contains keyword
    "RESET" (case-insensitive). Filter to contacts who already carry
    `myers-lead` so unrelated RESET texts don't fire this WF.
  WF-03 global reply handler: trigger = Customer Replied. Filter to
    contacts currently in WF-01 (or carrying `myers-lead` and NOT carrying
    `myers-replied` yet). This is the WF that pages the front desk.

Generated by `/build-sequence iv-wellness-myers-cocktail` from offer spec at
Notion page 34f72879-5ff0-817d-be58-e43d635df733.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).

Hard rules (IV strict mode):
- "Supports / helps with / patients often describe" only. Never treats /
  cures / fixes.
- No before/after photos (no MMS at T+1).
- No em dashes anywhere in body SMS/email strings.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site RN.
- Real testimonials only or unnamed composites.
- No deadline on this offer (Has Deadline=No), so D10 email uses
  Zeigarnik-style "compounding wellness" framing instead of urgency.
- Myers is the entry-level IV (~30-45 min, $175). Cross-sell tee-up toward
  NAD+ or monthly membership lands in D10/D14/D28 messaging for the clients
  who feel the lift and want more.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, one quick question before I send you anything"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the Myers Cocktail. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. We do mobile IVs, meaning a licensed RN comes to your home or office, sets up in about 10 minutes, and you sit comfortably for the 30 to 45 minute drip.

One question before I send anything else, because your answer changes what's useful to you:

**Are you looking at the Myers for a general energy and immune recharge, or is there something specific you're trying to feel better from (post-travel, fighting something off, run-down stretch)?**

Reply with "general" or with the specific reason. One word is enough.

In the meantime, here's what your first session looks like:

- Free pre-drip wellness assessment, the RN confirms the Myers is the right call for you that day
- $175 for the full Myers Cocktail (magnesium, calcium, B-vitamins, vitamin C)
- Mobile setup within 20 miles of Cincinnati, no clinic visit, no wait

Pricing and the full menu are on our site so there are no surprises.

[See Available Times]({{custom_values.booking_link}})

Not ready to book? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""


E2_SUBJECT = "The 3 questions I get most about the Myers Cocktail"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone reaches out about the Myers. Honest answers below, including the part most places skip.

**1. What makes this different from just taking vitamins?**
Oral vitamins go through your digestive system, and absorption rates for B-vitamins, magnesium, and vitamin C drop off fast, especially when you're already run-down. The Myers delivers the same nutrients straight into your bloodstream rather than being filtered through digestion first, so the formula reaches your cells directly. That's the whole reason this formula has been used in clinics for 50+ years. It's the original IV cocktail.

**2. How quickly will I feel it?**
Patients often describe a noticeable lift the same evening or next morning, usually energy and a sense of clarity. Some feel it during the drip. The Myers is the broadest, most accessible IV we run, so the response is steady rather than dramatic. If you want a stronger or more targeted lift later, we have NAD+ and other formulas, but most first-timers start here for a reason.

**3. Do I need a prescription?**
No. The wellness consult with the licensed RN at the start of your session covers everything. She reviews your meds, current state, and any past IV history. If anything is a flag, she tells you straight and we don't run the drip. You don't pay for one that isn't a fit.

One honest thing about us. The vitamin C in the bag has a slight metallic or "vitamin" taste that some people notice for a minute or two during the push. It fades fast. Anyone who tells you it's totally unnoticeable is overselling it.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing first-time Myers clients say most often after their session surprised me the first time I heard it. I'll tell you about it in a few days.

{{custom_values.text_message_name}}"""


E3_SUBJECT = "4 things to do before any IV session (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Four small things that make any IV session work better, true with us or anywhere else.

**1. Hydrate hard the day before.**
Aim for 80 to 100 oz of water. Any IV runs better when you're already topped off, and the stick is easier when your veins are showing up.

**2. Eat a real meal about 60 minutes before.**
Not a granola bar, not just coffee. Empty stomach plus IV is the quickest way to feel lightheaded, especially with the Myers because the magnesium can drop your blood pressure slightly during the push.

**3. Skip caffeine that morning.**
The Myers is the energy lift here, you don't need to stack it with coffee. Most people feel sharper without the caffeine layered on top.

**4. Block 60 minutes total, not just the drip time.**
Setup, the wellness consult, and the actual 30 to 45 minute drip. You don't want to be watching the clock, the calmest sessions feel the best.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E4_SUBJECT = "She came in just to try it once"
E4_BODY = """Hi {{contact.first_name}},

A client reached out last winter. Mid-30s, working mom, told me she'd been "running on fumes" since the holidays. Sleep was fine, eating was fine, but she felt like she couldn't catch up. She'd never done an IV before. Booked one Myers session, said she'd see how it went.

Her message that night, copy-pasted from the follow-up text:

*"I just put the kids to bed and I still have energy. That hasn't happened in months. Booking another one for next week."*

She came back the following week, then signed up for monthly maintenance after the third session.

The thing she told me after that stuck. She said she didn't feel "supercharged" or anything dramatic. She just felt normal again. The Myers isn't a stimulant, it's a refill. Most first-timers describe it that way, "this is how I should already be feeling, I just hadn't noticed how off I was."

Reply "menu" and I'll send the full IV menu if you want to see what we offer alongside the Myers. Or if you've got a question, send it.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""


E5_SUBJECT = "Remember when I said the Myers surprises people?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing first-time Myers clients say most often after their session.

Here it is:

*"I didn't know how depleted I was until I wasn't anymore."*

That sentence shows up in our exit feedback about once a week, almost word for word. People come in expecting a dramatic energy hit and what they get instead is a baseline reset. They realize how long they'd been calling normal "fine" when their body was actually running below the line.

Most of our Myers regulars didn't think they needed support. They came in for a one-off recharge after a rough week or before a trip, and they kept coming back because they couldn't unfeel the difference.

I'm not going to push you. If now isn't the right time, that's real. But if you've been telling yourself you'd book it "after this week" or "when things slow down," that line is the one keeping you exactly where you are.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E6_SUBJECT = "Why one Myers tells you what monthly does"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most people treat the Myers like a one-time experiment. Try it once after a hard week, see how it feels, decide later. That's a fine way to test the floor of how it works. It is not where the real value lives.

Here's the part that surprises clients:

**Your nutrient levels for B-vitamins, magnesium, and vitamin C fluctuate constantly with stress, sleep, illness, alcohol, and travel.** A single Myers session moves you noticeably back toward a higher baseline. That window of feeling clear and steady lasts a few days for most people, then it fades, because your body burns through it.

**Monthly Myers is what compounds.** Each session puts the formula back in before the previous one has fully tapered. The lift gets longer-lasting, the run-down stretches between sessions get shorter, and you stop hitting those weeks where you feel like you're dragging.

**A first-timer who books one session and tries to evaluate the protocol from there is grading the wrong test.** The single session shows you it works. Monthly shows you what staying topped off actually does for your week-to-week energy.

That's the actual math. Not "you'll feel like a million bucks." Just "your body's nutrient floor stays high enough that the run-down weeks stop catching you off guard."

If the single session lands well for you, the RN talks you through monthly options on the spot, no pressure either way. The free wellness assessment is still on the table for your first session. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""


E7_SUBJECT = "Last email from me, plus my direct line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

People wait for a reason. The most common ones I hear:

- "I'll book when I'm not so busy" (you won't be, the calendar doesn't clear)
- "I want to see if I really need it first" (the only way to know is one session, and the wellness assessment is included)
- "I'm not sure if the Myers is right for me" (that's literally what the on-site assessment is for, and it's free)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Book directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and gets you straight to a slot.

Whatever you decide, thanks for considering us.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your Myers Cocktail request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you looking at the Myers for a general recharge or for something specific (post-travel, fighting something off, run-down)?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent you a welcome email with the rundown. Same question there, general recharge or something specific? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown for first Myers sessions. Takes 2 min to read. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab a Myers slot for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, most first-time Myers clients are surprised by one specific thing (and it isn't the energy hit). Mind if I share?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the Myers? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text RESET to this number and I'll get the RN on the calendar that week. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your Myers file or keep it open for whenever you're ready? If a stronger drip like NAD+ would fit better, just say so and I'll send that menu."


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the calendar. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the booking link worked. Want me to grab a Myers slot for you directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on Myers Cocktail nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the Myers Cocktail nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or rebooked.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from FB form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (general vs specific)
#   D1 10a  E1              welcome + qualifying Q echo
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              objections + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (rundown offer)
#   D3 10a  E3              quick-win prep tips
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof story
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 5p   SMS_D5_5pm      curiosity gap
#   D7 10a  E5              Zeigarnik close
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              monthly compounding math (no deadline framing)
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup + NAD+ tee-up
#   tag     myers-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. Myers Cocktail — Master Sequence",
        "tag": "myers-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q General vs Specific (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Quick-Win Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Social Proof Story (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Depleted Until Not (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 Monthly Compounding Math (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + RESET Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup + NAD+ Tee-Up (D28 10am)", SMS_D28_10am),
            tag_step("Mark Myers Nurture Complete", ["myers-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. Myers Cocktail — RESET Keyword Recovery",
        "tag": "myers-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["myers-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["myers-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. Myers Cocktail — Global Reply Handler",
        "tag": "myers-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["myers-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"Myers Cocktail Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="Myers Cocktail — The Ultimate Recharge IV",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
