#!/usr/bin/env python3
"""
IV Wellness — Glutathione Glow Drip nurture sequence (28-day, linear).

Trigger: Facebook Lead Ads form submission (set the trigger source in GHL UI
to the FB form for the Glutathione Glow campaign; this script tags the lead
with `glutathione-lead` so the standard tag-add trigger picks it up).

Generated by `/build-sequence iv-wellness-glutathione-glow` from offer spec at
Notion page 34f72879-5ff0-8146-8662-d1d13d70f1ed.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).

Hard rules (IV strict mode):
- "Supports / helps with / patients often describe" only. Never treats / cures / fixes.
- No before/after photos (no MMS at T+1).
- No em dashes anywhere.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site RN.
- Real testimonials only or unnamed composites.
- Glutathione protocol: tee up the 3-session package in days 14-28 (single
  session shows you it works, the 3-pack shows you what it actually does).
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, one quick question before I send you anything"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the Glutathione Glow Drip. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. We do mobile IVs, meaning a licensed RN comes to your home or office, sets up in about 10 minutes, and you sit comfortably for the 30 to 45 minute push.

One question before I send anything else, because your answer changes what's useful to you:

**Are you exploring Glutathione for general skin brightening and antioxidant support, or is there something specific you're trying to address (dark spots, dull tone, post-sun damage)?**

Reply with "general" or with the specific concern. One word is enough.

In the meantime, here's what your first session looks like:

- Free pre-drip wellness assessment, the RN confirms Glutathione is the right call for you that day
- $175 high-dose Glutathione IV push
- Optional Vitamin C add-on at the time of service if you want to stack the antioxidant support

Pricing and the full menu are on our site so there are no surprises.

[See Available Times]({{custom_values.booking_link}})

Not ready to book? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""


E2_SUBJECT = "The 3 questions I get most about Glutathione"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone reaches out about the Glow Drip. Honest answers below, including the part most places skip.

**1. Does it actually brighten skin?**
Glutathione is the body's master antioxidant. It supports the pathway your skin uses to manage melanin and oxidative stress. Patients often describe a more even tone and a noticeable "lit from within" look starting after the second or third session. A single session is a real test of how your skin responds, but the visible shift most people are after shows up with a short series.

**2. Is it safe?**
Your first session includes a full wellness assessment by a licensed RN before anything goes in. She reviews your meds, current state, and any past IV history. If anything is a flag, she tells you straight and we don't run the drip. You don't pay for one that isn't a fit.

**3. How many sessions do I need?**
One session shows you the response. The 3-session protocol over 3 to 4 weeks is what most clients describe as the visible shift. After that, monthly maintenance keeps the effect steady. We don't push the package on the first visit, the RN talks you through what makes sense once she sees how your skin responds to round one.

One honest thing about us. Glutathione has a faint sulfur smell during the push, some people notice a metallic taste for a minute or two. Anyone who tells you it's totally unnoticeable is overselling it. The smell fades fast and the rest of the session is uneventful.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing first-time Glutathione clients say most often after their session surprised me the first time I heard it. I'll tell you about it in a few days.

{{custom_values.text_message_name}}"""


E3_SUBJECT = "4 things to do before any Glutathione session (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Four small things that make any Glutathione session work better, true with us or anywhere else.

**1. Hydrate hard the day before.**
Aim for 80 to 100 oz of water. Glutathione runs better when you're already topped off, and the IV stick is easier when your veins are showing up.

**2. Skip alcohol the night before.**
Glutathione is the antioxidant your liver leans on hardest after drinks. If you load it the morning after a wine night, most of it gets pulled into recovery work instead of the skin support you booked it for.

**3. Eat a light meal about 60 minutes before.**
Empty stomach plus IV is the quickest way to feel lightheaded. Doesn't need to be big, just real food.

**4. Skip retinoids and exfoliating acids for 48 hours after.**
Your skin is in a heightened antioxidant state for a day or two. Layering actives on top is unnecessary and can leave your skin feeling sensitized.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E4_SUBJECT = "She came in just to try it once"
E4_BODY = """Hi {{contact.first_name}},

A client reached out last summer. Late 30s, told me her skin had been looking "tired" for months. No specific issue, just a slow drift toward dull. She'd already tried the serums, the new acid toner, two facials. She booked one Glutathione session, said she'd see how it went.

Her message two days later, copy-pasted:

*"My makeup is sitting differently. My husband asked if I changed my skincare. I haven't, that was just the one drip."*

She came back for the 3-session package the following week. Now she does one a month.

The thing she told me after that stuck. She said the products she'd been buying were doing their job on the surface, but they couldn't reach the layer where the dullness was actually coming from. Glutathione works from the bloodstream out, which is why it shows up where topical products plateau.

Reply "menu" and I'll send the full IV menu if you want to see what we offer alongside the Glow Drip. Or if you've got a question, send it.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""


E5_SUBJECT = "Remember when I said Glutathione surprises people?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing first-time Glutathione clients say most often after their session.

Here it is:

*"I expected to see something in the mirror. I didn't expect to feel different."*

That sentence shows up in our exit feedback about once a week, almost word for word. People come in for the skin and they leave noticing something else, a kind of clarity and lightness that they can't quite name. That's the antioxidant load lifting off. Most of them aren't tired in a way they'd ever flagged, they just hadn't realized how much their body had been carrying.

Most of our Glow Drip regulars didn't think they needed support. They came in for the visible result and stayed for the way they felt afterward.

I'm not going to push you. If now isn't the right time, that's real. But if you've been telling yourself you'd book it "after the next paycheck" or "when things slow down," that line is the one keeping you exactly where you are.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E6_SUBJECT = "Why the 3-session protocol matters more than the first one"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most people treat Glutathione like a one-time experiment. Try it once, see if the skin shifts, decide later. That's a fine way to test the floor of how your body responds. It is not how the protocol actually works.

Here's the part that surprises clients:

**Glutathione levels in your body fluctuate daily and decline with age, sun exposure, stress, and alcohol.** A single session moves you noticeably back toward a higher antioxidant baseline. That window of supported skin and lifted oxidative load lasts a few days for most people, then it fades, because your body burns through it.

**The 3-session protocol over 3 to 4 weeks is what compounds.** Each session puts more Glutathione into the system before the previous push has fully tapered. The skin shift gets visible, the gap between sessions widens, and you settle into a maintenance cadence that's usually monthly.

**A first-timer who books one session and tries to evaluate the protocol from there is grading the wrong test.** The single session shows you it works. The 3-session series shows you what it actually does.

That's the actual math. Not "you'll glow like a movie star." Just "your skin's antioxidant defense system gets supported in a way topicals can't reach, and the visible difference lands in the second to third week."

The free wellness assessment and the optional Vitamin C add-on are still on the table for your first session. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""


E7_SUBJECT = "Last email from me, plus my direct line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

People wait for a reason. The most common ones I hear:

- "I'll book when I'm not so busy" (you won't be, the calendar doesn't clear)
- "I want to see if I really need it first" (the only way to know is one session, and the wellness assessment is included)
- "I'm not sure if Glutathione is right for me" (that's literally what the on-site assessment is for, and it's free)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Book directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and gets you straight to a slot.

Whatever you decide, thanks for considering us.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your Glutathione Glow request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you exploring the Glow Drip for general skin brightening or for something specific (dark spots, dullness, post-sun)?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent you a welcome email with the rundown. Same question there, are you after general brightening or a specific concern? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown for first Glutathione sessions. Takes 2 min to read. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab a Glow Drip slot for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, most first-time Glutathione clients are surprised by one specific thing (and it isn't the skin). Mind if I share?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the Glow Drip? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text RESET to this number and I'll get the RN on the calendar that week. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your Glow Drip file or keep it open for whenever you're ready?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the calendar. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the booking link worked. Want me to grab a Glow Drip slot for you directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on Glutathione Glow nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the Glutathione Glow Drip nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or rebooked.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from FB form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (general vs specific concern)
#   D1 10a  E1              welcome + qualifying Q echo
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              objections + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (rundown offer)
#   D3 10a  E3              quick-win prep tips
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof story
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 5p   SMS_D5_5pm      curiosity gap
#   D7 10a  E5              Zeigarnik close
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              3-session compounding math
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     glutathione-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. Glutathione Glow — Master Sequence",
        "tag": "glutathione-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q General vs Specific (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Quick-Win Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Social Proof Story (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Lit From Within (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 3-Session Compounding Math (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + RESET Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark Glutathione Nurture Complete", ["glutathione-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. Glutathione Glow — RESET Keyword Recovery",
        "tag": "glutathione-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["glutathione-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["glutathione-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. Glutathione Glow — Global Reply Handler",
        "tag": "glutathione-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["glutathione-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"Glutathione Glow Drip Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="Glutathione Glow Drip — Skin Brightening IV",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
