#!/usr/bin/env python3
"""
IV Wellness — IV Wellness Membership nurture sequence (28-day, linear).

Trigger swaps to make in the GHL UI before going live:
1. WF 01 trigger: this script seeds tag `membership-lead`. In the GHL UI swap
   the tag-add trigger for the upstream Facebook Lead Ads form (or whatever
   form captures membership interest). The tag stays as the audience filter.
2. WF 02 trigger: swap the tag-add trigger for an inbound SMS keyword filter
   matching `MEMBER` (case-insensitive) on the location's main number. The
   keyword tag `membership-keyword-trigger` is the downstream audience filter.
   (Keyword for this workflow is MEMBER, not RESET.)
3. WF 03 trigger: swap the tag-add trigger for "Customer Replied" filtered to
   contacts who completed WF 01 (i.e. carry the `membership-lead` tag and have
   not been manually marked resolved).

Generated by `/build-sequence iv-wellness-membership` from offer spec at
Notion page 35372879-5ff0-81a8-9fc9-d83bd90e955f.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).

Hard rules (IV strict mode):
- "Supports / helps with / patients often describe" only. Never treats / cures / fixes.
- No before/after photos (no MMS at T+1).
- No em dashes anywhere in body copy.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site PA/RN.
- {{location.name}} / {{location.phone}} / {{location.address}} for clinic info.
- {{custom_values.booking_link}} for the calendar link.
- Real testimonials only or unnamed composites.
- Membership psychology: subscription commitment matters more than scarcity.
  Lean on trust, predictability, cancel-anytime flexibility, and member-only
  pricing math. No fake deadlines (Has Deadline=No on this offer).
- Audience assumption: most members start as one-off IV clients. Reference
  the experience they already had. Do not pitch as cold-from-zero.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, one quick question before I send you anything"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the IV Wellness Membership. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. Most of the people who ask about the membership have already had at least one IV with us, so apologies if some of this is review.

One question before I send the rest, because your answer changes what's useful to you:

**Are you looking at the membership for steady monthly wellness, or are you trying to sort out a specific stretch (heavy travel season, recovery from a rough quarter, training cycle)?**

Reply with "monthly" or with the situation. One word is enough.

In the meantime, here is what the membership actually is, plain text:

- $299 per month, cancel any time
- 2 signature IV infusions per month, your choice from the menu
- 1 free add on per IV (red light, compression boots, or PEMF mat, $20 value each)
- Member pricing on extra IVs at $149 each
- Sign up bonus: bring a friend free for one infusion, plus 50% off NAD+ injections for your first 2 months

Pricing is on the site, no surprises and no contracts.

[See Available Times]({{custom_values.booking_link}})

Not ready to enroll? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""

# *Subject pattern: question. Soft CTA + segmenting question. Opens with the
# audience truth (already IV-experienced). Lays out included items as plain
# bullet list so the math is visible.*


E2_SUBJECT = "The 3 questions I get most about the membership"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone asks about the IV Wellness Membership. Honest answers below, including the parts most clinics skip.

**1. What if I miss a month, or I'm traveling?**
Your 2 IVs reset on the first of each month. They don't roll over, so the membership rewards consistency. If you're traveling, the smart play is to schedule your second IV early in the month before you leave. If life happens and you only get one in a given month, that's on you, not a refund situation. Most members average between 1.8 and 2.2 IVs a month over a quarter.

**2. Am I locked in long term?**
No. Cancel anytime. No 6 month contract, no cancellation fee, no "we'll keep billing for one more cycle" trick. You text us, we end the billing the next cycle. We'd rather lose a member who isn't getting value than keep one resentfully.

**3. What actually counts as a session?**
Any signature IV on the menu. The Myers, the Immunity drip, the Recovery drip, the Beauty drip, all in. NAD+ infusions are not in the included 2 (they are their own protocol and pricing), but you get 50% off NAD+ injections for your first 2 months as a sign up bonus, and members get the $149 price on additional standard IVs after their 2 included.

One honest thing about us. We are not a franchise. The PA on site is Brittany, and our protocol was built by the founder who is a CRNA with 20+ years of nursing experience. The flip side of that is we have one location and we operate around our PA's schedule, so prime time slots fill 5 to 7 days out. If you need something same week, book on the early side.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing members tell me at month 3 that they didn't expect at sign up? I'll share it in a few days.

{{custom_values.text_message_name}}"""

# *Subject pattern: specificity. Handles the top 3 membership-specific
# objections directly (miss a month, lock in, what counts). Pratfall is
# operational (one location, prime slots fill). Zeigarnik teaser closes in D7.*


E3_SUBJECT = "How members actually use the 2 IVs each month"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Here is how our most consistent members actually use their 2 included IVs each month, in case it helps you picture whether the math fits your life.

**Pattern 1: The split (most common).**
One IV in the first week of the month, usually the Myers cocktail or Immunity drip. The second one mid-month, often the Beauty drip with the red light add on, or the Recovery drip after a heavy training stretch. Two distinct uses, two distinct results. This is the "monthly baseline" cadence.

**Pattern 2: The double down.**
Both IVs back to back over a 7 to 10 day stretch. Travel coming up, big work week, a stretch of poor sleep. The compounding effect of two IVs close together is what most members describe as the "actually feel different" moment. Then they take a couple weeks at baseline before the next month.

**Pattern 3: The strategic.**
Members who track this stuff (training cycles, travel calendars, hormone patterns) plan their 2 IVs around predictable dips. PA on site can help map this out at your first visit if you want to think about it that way.

A practical note: the free add on per IV (red light, compression boots, or PEMF mat) is a $20 value each, so that is $40 per month in services baked in before you count the IVs themselves. Most members forget to factor that in. We don't.

P.S. Whenever you want to start: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject pattern: how-to + specifics. Pure value, no sell. Reframes the 2 IVs
# from abstract benefit to concrete usage patterns. P.S. link only.*


E4_SUBJECT = "She came in for one IV last spring"
E4_BODY = """Hi {{contact.first_name}},

A client came in last spring. Late 30s, working mom, three kids. She booked one IV after a week of "feeling like I was running on fumes." She did the Myers cocktail with a B12 push, told us she'd see how it went.

Her message four days later, paraphrased from the follow up text:

*"I forgot what it felt like to not be exhausted by 3pm. Today's the third day in a row I haven't crashed. How do I do this regularly without it being a project every time?"*

That conversation is exactly why the membership exists. She enrolled the next week. She is now 8 months in.

What surprised me about her case wasn't the energy lift, that's pretty common. It was what she said at month 3:

*"I stopped negotiating with myself about whether I had time to come in. It just became the thing I do twice a month. The decision is made once, not 24 times a year."*

That is the hidden value of a membership for people who actually use it. The decision fatigue around taking care of yourself goes away. You stop debating, you just go.

If you've already done one or two IVs with us and you're wondering whether enrolling makes sense, that is exactly the moment most of our best members signed up. They had the data point that it worked, they just didn't want to keep manually rebooking.

Reply "menu" and I'll send the full IV menu so you can see what your 2 monthly IVs could look like across the year. Or if you have a question, send it.

[Lock In Your Membership Slot]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""

# *Subject pattern: story tease. Unnamed composite client (IV strict mode).
# Uses the "decision fatigue" angle, which is membership-specific and not in
# the one-off IV nurtures. Targets the audience truth (already had ≥1 IV).*


E5_SUBJECT = "Remember when I said members surprise themselves at month 3?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing members tell me at month 3 that they didn't expect at sign up.

Here it is:

*"It's not the IV days that changed things. It's the days in between."*

That sentence shows up in our member check ins about once a month, almost word for word. People expect the membership to make IV days feel great. The actual surprise is that the days between IVs change too. The mid month dip stops being so deep. The recovery from a hard week is faster. The afternoon energy crash gets quieter. Not gone, quieter.

The reason is straightforward. One IV is a single point of input. Two IVs a month is a steady drip of inputs that keep you closer to your own baseline instead of letting you slide and then resetting. That gap between sliding and resetting is where most people spend their lives, and they don't realize it until it shrinks.

I'm not going to push you. If now isn't the right time for a monthly commitment, that's real and the IVs are still here a la carte at $179 each.

But if you've been telling yourself "I should do this regularly," the membership exists precisely to remove the friction between "I should" and "I did." The math at $299 for 2 IVs plus 2 free add ons works out to about $130 per session, which is below our a la carte rate before you even count the bonuses.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject pattern: curiosity + permission. Closes Zeigarnik loop from D2.
# The "days in between" angle is membership-unique. Surfaces the per-session
# math without forcing a comparison the lead has to do themselves.*


E6_SUBJECT = "The math most people don't run before saying no"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

People say no to the membership for one of two reasons. Either they're not sure it'll work for them, which is a fair concern and one IV usually answers it. Or they don't want another monthly bill on the card, which I get completely.

But here is the math that almost nobody runs before deciding:

**What you're already spending on feeling functional, monthly.**
Coffee runs (4 per week, $6 each): $96
Energy drinks or pre-workout: $40 to $80
Supplements that don't quite stick (the rotating cabinet): $40 to $100
Recovery anything (massage, sauna day pass, etc.): $50 to $150
Random "treat myself" wellness purchases: $30 to $80

Most of our members were spending $250 to $400 a month on things they hoped would help them feel better, before they enrolled. The membership is $299 and replaces a meaningful chunk of that with two PA supervised infusions, which is what they were trying to manufacture with the coffee and the supplements in the first place.

Then the bonuses on top:
- 2 IVs at member price ($179 a la carte each, $130 per session inside the membership, you save roughly $98 a month)
- 2 free add ons ($40 a month value)
- Sign up bonus for new members: bring a friend free, plus 50% off NAD+ injections for your first 2 months

The 6 month math, if you stay 6 months: roughly $1,800 in for roughly $2,200 in services received. The 12 month math is better. Cancel any time if it stops working for you.

I'm not telling you the membership is the right call. I'm telling you not to say no without running this against what's already on your card.

The free PA assessment and the included add ons are still there for your next IV. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""

# *Subject pattern: curiosity + cost reframe. Logic + cost-of-not-deciding.
# Membership-specific: the math is the entire pitch here. No fake deadline
# (Has Deadline=No). Cancel-any-time keeps the trust frame intact.*


E7_SUBJECT = "Last email from me, plus my direct line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

Members enroll for a reason. The most common ones I hear:

- "I want to see if I really need it first" (you've probably had at least one IV with us, you have the data point)
- "I don't want another monthly bill" (cancel any time, no fee, no contract, the math usually works in your favor anyway)
- "I want to check with my partner" (totally fair, the membership is also gift able and partners often split it)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Enroll directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **MEMBER**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and gets you straight to your membership setup.

Whatever you decide, thanks for considering us. If membership is the right fit, you can start anytime. Message me with MEMBER and I'll send the link.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""

# *Subject pattern: direct. Phone + KEYWORD as CTA, no button. Permission-to-stop.
# No urgency anchor (Has Deadline=No on this offer).
# This is the message people screenshot.*


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your IV Wellness Membership request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you looking at the membership for steady monthly wellness or for a specific stretch (travel, training, recovery)?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent the welcome email with the rundown. Same question there, monthly baseline or a specific stretch? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown on how members actually use their 2 monthly IVs. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab your first member IV slot for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, members usually surprise themselves at month 3 with one specific thing. Mind if I share what it is?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the membership? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text MEMBER to this number and I'll get your membership set up that week. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your membership inquiry or keep it open for whenever you're ready?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_MEMBER_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the membership setup. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_MEMBER_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the membership link worked. Want me to walk you through enrollment directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on IV Wellness Membership nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the IV Wellness Membership nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or enrolled.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (monthly vs specific stretch)
#   D1 10a  E1              welcome + qualifying Q echo + included items
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              top 3 membership objections + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (usage rundown offer)
#   D3 10a  E3              how members actually use the 2 IVs
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof (decision fatigue angle)
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 5p   SMS_D5_5pm      curiosity gap (month 3 surprise)
#   D7 10a  E5              Zeigarnik close (days in between)
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              cost-reframe math (vs current spend)
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + MEMBER keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     membership-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. IV Wellness Membership — Master Sequence",
        "tag": "membership-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q Monthly vs Stretch (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Membership Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 How Members Use The 2 IVs (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Decision Fatigue Story (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap Month 3 (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Days In Between (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 Cost Reframe Math (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + MEMBER Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark Membership Nurture Complete", ["membership-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. IV Wellness Membership — MEMBER Keyword Recovery",
        "tag": "membership-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["membership-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["membership-nurture-complete"], remove=True),
            sms_step("MEMBER Auto-Reply with Booking Link", SMS_MEMBER_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("MEMBER 2-Hour Follow-Up", SMS_MEMBER_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. IV Wellness Membership — Global Reply Handler",
        "tag": "membership-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["membership-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"IV Wellness Membership Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="IV Wellness Membership",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
