#!/usr/bin/env python3
"""
IV Wellness — NAD+ IV Therapy nurture sequence (27 touchpoints, no deadline).

Trigger: contact gets tag `nadivtherapy-lead`.
Generated by `/build-sequence iv-wellness-nad-iv-therapy` from offer spec at
`offers/iv-wellness-nad-iv-therapy.md`.

Touchpoint count: 27 across 28 days (V2 Day 5 deadline email DROPPED because
`Has Deadline=No` on this offer).

Branch pair: wellness-curious vs symptom-driven (IV-specific, replaces DPN's
first-timer/burned-before pair). Linear default in workflow `01-master` is the
wellness-curious D4 variant and the Zeigarnik-close D7 variant. Branched
sub-workflows (D4 symptom-driven, D7 standalone) deploy as parallel WFs in the
GHL UI gated by `nadivtherapy-symptom-driven` and absence of
`nadivtherapy-opened-d2` respectively.

Manual touchpoints (D0 double-dial, D0 voicemail, D2 morning call, D2 afternoon
SMS, D3 afternoon call, D5 morning Hail Mary) live in
`clients/iv-wellness/nad-iv-therapy-manual-touchpoints.md`. They are NOT
automated and do NOT appear in this file.

Hard rules (IV strict mode):
- "Supports / helps with / patients often describe" only. Never treats / cures / fixes.
- No before/after photos (no MMS at T+1).
- No em dashes anywhere.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site RN.
- Real testimonials only (Erin, Abby, Michelle) or unnamed composites.
- No Care Credit / financing.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, quick question before I send you anything"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about NAD+. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. We do mobile NAD+ infusions, meaning a licensed RN comes to your home or office, wherever you'd actually want to sit for the 90 to 120 minute session.

One question before I send you anything else, because your answer changes what's useful to you:

**Are you exploring NAD+ for general wellness and longevity, or is there something specific you're trying to feel better from?**

Reply with "wellness" or with the symptom (tired, foggy, recovery, whatever it is). One word is enough.

In the meantime, here's what your first session looks like:

- Free pre-session wellness assessment, the RN confirms NAD+ is the right call for you that day
- $399 NAD+ 250mg session
- Free B12 or Glutathione push with your first session, your choice

Pricing and the formula menu are on our site so there are no surprises.

[See Available Times]({{custom_values.booking_link}})

Not ready to book? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""

# *Subject pattern: question. Preview extends. Soft CTA + segmenting question. Reciprocity via free wellness check.*


E2_SUBJECT = "The 3 questions I get most about NAD+"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone reaches out about NAD+. Honest answers below, including the part most places skip.

**1. Is it safe?**
Your first session includes a full wellness assessment by a licensed RN before anything goes in. She reviews your meds, current state, and any past IV history. If anything is a flag, she tells you straight and we don't run the session. You don't pay for one that isn't a fit.

**2. How is this different from a B12 shot?**
Honest answer, very different. B12 is one nutrient injected into muscle. NAD+ is a coenzyme delivered IV directly into your bloodstream over 90 to 120 minutes. NAD levels drop about 50% by age 50, so the IV supports cellular energy production in a way a B12 shot can't reach. The free B12 or Glutathione push you get with your first session is on top of the NAD+, not instead of.

**3. Will I really feel the difference?**
Patients often describe a noticeable energy and clarity lift within 24 to 48 hours after the first session. Some feel it during. The protocol works best as 3 to 4 sessions in the first month, but a single one is a real test.

One honest thing about us. NAD+ at full dose burns. Your chest feels warm and your face flushes for the first 20 minutes. We slow the drip way down at the start, but anyone who tells you it's totally comfortable is lying. The rest of the session is fine.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing first-time NAD+ clients say most often after their session surprised me the first time I heard it. I'll tell you about it in a few days. It comes up almost every week now.

{{custom_values.text_message_name}}"""

# *Subject pattern: specificity. Handles top 3 objections. Pratfall (the flush). Zeigarnik teaser at the end (closes in D7).*


E3_SUBJECT = "4 things to do before any NAD+ session (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Four small things that make any NAD+ session work better, true with us or anywhere else.

**1. Hydrate hard the day before.**
Aim for 80 to 100 oz of water. NAD+ runs better when you're already topped off, and the IV stick is easier when your veins are showing up.

**2. Eat a real meal about 60 minutes before.**
Not a granola bar, not just coffee. Empty stomach plus NAD+ leaves some people lightheaded in the first 20 minutes when the flush hits hardest.

**3. Block the full 2 hours.**
NAD+ is not a session you squeeze between meetings. Plan to sit for the whole thing. Trying to take a call mid-drip is the most common regret first-timers report.

**4. Skip caffeine that morning.**
NAD+ is the energy lift here, you don't need to stack it with coffee. Most people feel sharper without the caffeine layered on top.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject pattern: how-to + number. Pure value, no sell. P.S. link only, no button. Reciprocity.*


# Linear default = wellness-curious variant (Branch A from iv-adjustments).
# Symptom-driven variant deploys as parallel sub-workflow gated by `nadivtherapy-symptom-driven`.
E4_SUBJECT = "She came in just to try it once"
E4_BODY = """Hi {{contact.first_name}},

A client reached out last fall. Mid-40s, no specific symptom, just curious about NAD+ after reading something on longevity. She booked one session, told us afterward she'd see how it went.

Her words on the way out, copy-pasted from the follow-up text:

*"That's the clearest my head's been in months. I don't know what I was running on but it wasn't this."*

She went on to do the 3-4 session first-month protocol. Now she comes monthly.

The thing she told me after that stuck. She wasn't tired. She just hadn't realized she was drifting through her days at 70%. She didn't know what fully on felt like anymore.

NAD+ doesn't do anything dramatic. It restores baseline. Most first-timers describe it the same way she did, "this is how I should already be feeling."

Reply "formulas" and I'll send the menu of what we offer alongside NAD+ if you want to see the full list. Or if you've got a question, send it.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""

# *Subject pattern: story tease. Wellness-curious branch (default). Unnamed composite client per IV compliance. "Reply formulas" replaces "reply photos" per IV strict mode.*


# Symptom-driven variant for parallel sub-workflow deploy
E4_SYMPTOM_SUBJECT = "When fatigue isn't from the obvious thing"
E4_SYMPTOM_BODY = """Hi {{contact.first_name}},

A client reached out last spring. Late 40s, told me she'd been tired for almost a year. Slept fine, ate fine, exercised, blood work came back unremarkable. She said she felt 10 years older than she was.

The RN ran a wellness assessment first. Cleared her for NAD+ 250mg. We added the free Glutathione push.

Her message the next morning:

*"First night in months I didn't wake up at 3am. Today's the first day I haven't needed an afternoon coffee."*

She's two months into the protocol now. The RN walked her through tapering after the first month.

The reason most of our NAD+ clients come in isn't a diagnosis. It's that "fine on paper, off in their body" feeling that bloodwork doesn't catch. NAD+ supports cellular energy specifically, which is why it often shows up where caffeine, sleep changes, and supplements have already plateaued.

If something specific brought you here, reply and tell me what it is. The free wellness assessment is what tells us if NAD+ is the right call for you that day, or if something else fits better.

[See Available Times]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""

# *Subject pattern: story tease. Symptom-driven branch. Targeted relief framing. Stronger CTA per iv-adjustments.*


# Variant B for non-openers (D1/D2 not opened)
E4B_SUBJECT = "Did my last two emails land?"
E4B_BODY = """Hi {{contact.first_name}},

Inbox filters are aggressive. Short version here.

Your first NAD+ session with us:
- Mobile setup, the RN comes to your home or office within 20 miles of Cincinnati
- Licensed RN, free wellness assessment before anything goes in
- $399 for the 250mg NAD+ session
- Free B12 or Glutathione push, your choice
- Session runs 90 to 120 minutes

The most common thing I hear from people on the fence is "will I actually feel anything different." Patients often describe a noticeable lift within 24 to 48 hours. The wellness assessment is what tells us straight if NAD+ is the right call that day.

Reply "formulas" and I'll send the full menu if you want to compare options.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}} · {{location.phone}}"""

# *Subject pattern: direct re-subject. Restates offer. Same micro-CTA pattern.*


# Linear default = E5a Zeigarnik close. E5b standalone deploys as parallel sub-workflow gated by absence of `nadivtherapy-opened-d2`.
E5_SUBJECT = "Remember when I said NAD+ surprises people?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing first-time NAD+ clients say most often after their session.

Here it is:

*"I didn't know I was running on empty until I wasn't."*

That sentence shows up in our exit feedback about once a week, almost word for word. People aren't surprised by the session itself. They're surprised by the gap, how off-baseline they'd been without realizing.

Most of our NAD+ regulars didn't think they needed support. They came in for a one-off, sat through the 90 minutes, and afterward realized they'd been calling exhaustion "just busy" or "just my age" for months.

I'm not going to push you. If now isn't the right time, that's real. But if you've been telling yourself you'd come in "when things slow down," that line is the one keeping you exactly where you are.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject pattern: curiosity + permission. Closes Zeigarnik loop from D2. Low-friction reply ask + main CTA.*


# Standalone variant for non-openers of D2
E5B_SUBJECT = "What's actually holding you back? (no pressure)"
E5B_BODY = """Hi {{contact.first_name}},

Genuine question. What's actually stopping you from booking the NAD+ session?

If it's safety, the RN does a full wellness assessment on-site before mixing anything. If your meds or current state are a flag, she won't run it and you don't get charged.

If it's the geography, we cover 20 miles around Cincinnati for mobile NAD+. Reply with your zip and I'll check.

If it's price, the first session is $399 and includes a free B12 or Glutathione push. After that the math gets better with the package.

If it's something else, reply and tell me. I read these.

[See Available Times]({{custom_values.booking_link}})

{{custom_values.text_message_name}} · {{location.phone}}"""

# *Subject pattern: direct. Standalone, no Zeigarnik reference (safe for non-openers of D2).*


E6_SUBJECT = "Why the first month matters more than the first session"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most people treat NAD+ like a one-time experiment. Try it once, see how it feels, decide later. That's a fine way to test the floor of how it works. It is not how the protocol actually works.

Here's the part that surprises clients:

**NAD+ levels drop roughly 50% by age 50, and they don't refill on their own.** A single session moves you noticeably back toward baseline. That window of feeling clear and steady lasts a few days for most people, then it fades, because your body is already drawing down again.

**The 3-to-4 session protocol in the first month is what compounds.** Each session puts more NAD+ into the system before the previous infusion has fully tapered. The lift gets longer-lasting, the gap between sessions widens, and you settle into a maintenance cadence that's usually monthly.

**A first-timer who books one session and tries to evaluate the protocol from there is grading the wrong test.** The single session shows you it works. The first month shows you what it actually does.

That's the actual math. Not "you'll feel like a million bucks." Just "your body's machinery for energy production starts running at the level it should already be at."

The free B12 or Glutathione push and the free wellness assessment are still on the table for your first session. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""

# *Subject pattern: curiosity + specificity. Logic + cost-of-inaction. No deadline framing (offer has no deadline). Compounding math instead.*


E7_SUBJECT = "Last email from me, plus my direct line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

People wait for a reason. The most common ones I hear:

- "I'll book when I'm not so busy" (you won't be, the calendar doesn't clear)
- "I want to see if I really need it first" (the only way to know is one session, and the wellness assessment is included)
- "I'm not sure if NAD+ is right for me" (that's literally what the on-site assessment is for, and it's free)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Book directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and gets you straight to a slot.

Whatever you decide, thanks for considering us.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""

# *Subject pattern: direct. Phone + KEYWORD as CTA, no button. Permission-to-stop. This is the message people screenshot.*


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your NAD+ request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you exploring NAD+ for general wellness, or is there something specific you're trying to feel better from?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent you a welcome email with the rundown. Same question there, are you exploring NAD+ for wellness or something specific? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown for first NAD+ sessions. Takes 2 min to read. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab a NAD+ slot for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, most first-time NAD+ clients are surprised by one specific thing. Mind if I share?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on NAD+? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text RESET to this number and I'll get the RN on the calendar that week. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your NAD+ file or keep it open for whenever you're ready?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the calendar. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the booking link worked. Want me to grab a NAD+ slot for you directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────
# Internal alert email body for front desk

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on NAD+ nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the NAD+ IV Therapy nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or rebooked.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from form submit, 27 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (wellness vs symptom)
#   D1 10a  E1              welcome + qualifying Q echo
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              objections + pratfall + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (rundown offer)
#   D3 10a  E3              quick-win prep tips
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof (wellness-curious default)
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 5p   SMS_D5_5pm      curiosity gap (NO deadline email since Has Deadline=No)
#   D7 10a  E5              Zeigarnik close (default linear)
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              compounding math + cost of waiting
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     nadivtherapy-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. NAD+ IV Therapy — Master Sequence",
        "tag": "nadivtherapy-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q Wellness vs Symptom (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Quick-Win Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Wellness-Curious Story (D4 10am default)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Running on Empty (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 Compounding Math + Cost of Waiting (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + RESET Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark NAD+ Nurture Complete", ["nadivtherapy-nurture-complete"]),
        ]),
    },

    # Branched sub-workflow: D4 symptom-driven variant.
    # Gated in GHL UI by `nadivtherapy-symptom-driven` tag.
    "01a-d4-symptom-variant": {
        "name": "01a. NAD+ IV Therapy — D4 Symptom-Driven Variant",
        "tag": "nadivtherapy-symptom-driven",
        "templates": link_steps([
            email_step("E4 Symptom-Driven Story (D4 10am branch)", E4_SYMPTOM_SUBJECT, E4_SYMPTOM_BODY, FROM_NAME),
        ]),
    },

    # Branched sub-workflow: D4 non-openers Variant B.
    # Gated in GHL UI by absence of `nadivtherapy-opened-d1` AND absence of `nadivtherapy-opened-d2`.
    "01b-d4-nonopener-variant": {
        "name": "01b. NAD+ IV Therapy — D4 Non-Opener Variant",
        "tag": "nadivtherapy-nonopener",
        "templates": link_steps([
            email_step("E4B Re-Subject for Non-Openers (D4 10am branch)", E4B_SUBJECT, E4B_BODY, FROM_NAME),
        ]),
    },

    # Branched sub-workflow: D7 standalone variant for non-D2-openers.
    # Gated in GHL UI by absence of `nadivtherapy-opened-d2` (so the Zeigarnik
    # loop reference doesn't land without context).
    "01c-d7-standalone-variant": {
        "name": "01c. NAD+ IV Therapy — D7 Standalone Variant",
        "tag": "nadivtherapy-d7-standalone",
        "templates": link_steps([
            email_step("E5B Standalone What's Holding You Back (D7 10am branch)", E5B_SUBJECT, E5B_BODY, FROM_NAME),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. NAD+ IV Therapy — RESET Keyword Recovery",
        "tag": "nadivtherapy-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["nadivtherapy-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["nadivtherapy-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. NAD+ IV Therapy — Global Reply Handler",
        "tag": "nadivtherapy-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["nadivtherapy-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"NAD+ IV Therapy Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="NAD+ IV Therapy Nurture",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
