#!/usr/bin/env python3
"""
IV Wellness — Skinny Drip Weight Loss IV Therapy nurture sequence (28-day, linear).

Trigger model (per `~/.claude/projects/.../project_iv_wellness_nad_workflow_rules.md`):
- WF-01 ships with a tag trigger `skinnydrip-lead` because the engine's
  automatic trigger creation only handles `contact_tag` types. The Facebook
  form submission trigger must be swapped in the GHL UI post-deploy
  (the FB form should add the `skinnydrip-lead` tag on submit, OR the
  WF-01 trigger should be edited from `Tag Added` to `Facebook Form
  Submission` after the deploy completes).
- WF-02 trigger is the inbound SMS keyword `RESET` (set up in GHL UI).
- WF-03 trigger is `Customer Replied` filtered to `replied to workflow =
  WF-01 Master Sequence` (set up in GHL UI after WF-01 ID is captured).

Generated by `/build-sequence iv-wellness-skinny-drip` from offer spec at
Notion page 34f72879-5ff0-8132-8367-f626608396c0.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).
Includes a D5 deadline email because `Has Deadline=Yes` on this offer.

Hard rules (IV strict mode + weight-loss compliance):
- "Supports / helps with / patients often describe" only. Never treats / cures / fixes.
- No weight-loss claims. No "lose X lbs". No "guaranteed results". No before/after photos.
- Frame as supporting metabolism, energy for workouts, hydration that complements
  a broader weight management plan (diet, movement, sometimes GLP-1).
- No em dashes anywhere in customer-facing body strings.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site RN.
- Pratfall up front: IVs alone don't drive weight loss. They support a deficit.
- Real testimonials only or unnamed composites. No financing.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, one quick question before I send the menu"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the Skinny Drip. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. We do mobile IVs, meaning a licensed RN comes to your home or office, sets up in about 10 minutes, and you sit comfortably for the 45 minute drip.

One question before I send anything else, because your answer changes what's useful to you:

**Are you currently on a weight management plan (GLP-1, keto, intermittent fasting, calorie deficit, training program), or are you exploring where to start?**

Reply with the plan name or "exploring." One word is enough.

Quick honest note up front. The Skinny Drip is not a magic shortcut. It is a blend of MIC, B-complex, carnitine, and chromium that supports your metabolism, energy through a deficit, and hydration that workouts depend on. It works best stacked with whatever weight management plan you're already running, not instead of one.

In the meantime, here's what your first session looks like:

- Free pre-drip wellness assessment, the RN confirms the Skinny Drip is the right call for you that day
- $199 Skinny Drip IV (MIC + B-complex + carnitine + chromium)
- Mobile setup, RN comes to you within 20 miles of Cincinnati
- 45 minute session start to finish

[See Available Times]({{custom_values.booking_link}})

Not ready to book? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""

# *Subject pattern: question + name. Pratfall up front (not magic). Soft CTA + qualifying Q.*


E2_SUBJECT = "The 3 questions I get most about the Skinny Drip"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone reaches out about the Skinny Drip. Honest answers below, including the part most places skip.

**1. Will this work if I don't diet?**
Honest answer, no. The Skinny Drip is not a fat-loss shortcut. It is a metabolic and energy support, MIC for fat metabolism support, B-complex for energy, carnitine to help your body use fat for fuel during activity, chromium for blood sugar steadiness. None of that creates a calorie deficit on its own. What it does is make the deficit you're already running easier to sustain. Anyone selling it as "lose weight without changing anything" is overselling.

**2. How often do I need it?**
Most clients start with one a week for 4 weeks while they're in the active phase of their weight management plan. After that, every 2 to 4 weeks for maintenance, or only on weeks where energy and recovery are getting hammered. The RN walks you through cadence after she sees how round one lands.

**3. Is it just a vitamin bag?**
No. A regular vitamin bag is hydration plus B-complex. The Skinny Drip adds MIC (methionine, inositol, choline, the lipotropic blend), carnitine, and chromium. Those are the ingredients that target metabolism and fat utilization specifically. The base vitamins are there too, but the formula is built for someone actively trying to manage weight, not just feel hydrated.

**4. Bonus, the part nobody tells you.**
The IV doesn't burn fat for you. It supports the work you're already doing. If you're not in a deficit, hydrating, or moving, the Skinny Drip on its own won't move the needle. Most clients pair it with GLP-1, structured eating, or a training block. That's where the math actually starts working.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing first-time Skinny Drip clients say most often after their session surprised me the first time I heard it. I'll tell you about it in a few days.

{{custom_values.text_message_name}}"""

# *Subject pattern: specificity. Handles all 3 stated objections + 4th honest disclaimer (pratfall). Zeigarnik teaser.*


E3_SUBJECT = "4 things to do before any Skinny Drip session (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Four small things that make any Skinny Drip session work better, true with us or anywhere else.

**1. Hydrate hard the day before.**
Aim for 80 to 100 oz of water. The drip absorbs better when you're already topped off, and the IV stick is easier when your veins are showing up.

**2. Eat a light protein-forward meal about 60 to 90 minutes before.**
Not a granola bar, not just coffee. The Skinny Drip on an empty stomach can leave people lightheaded, especially if you're already in a deficit. Some protein steadies the session.

**3. Plan to move within 24 hours after.**
Carnitine helps your body use fat for fuel during activity. The drip sits idle if you sit on the couch for the next two days. A walk, a workout, anything that gets your heart rate up gives the formula something to work with.

**4. Don't add it to a brand new plan in the same week.**
If you're starting a GLP-1, switching to keto, or beginning a new training block, give the new plan 7 to 10 days to settle in before stacking the drip. Otherwise you can't tell what's doing what.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject pattern: how-to + number. Pure value, no sell. P.S. link only. Reciprocity.*


E4_SUBJECT = "She added it to her GLP-1 routine and texted me a week later"
E4_BODY = """Hi {{contact.first_name}},

A client reached out late last year. Early 40s, six months into a GLP-1 program, doing everything right on paper. Her message said the scale was moving but the energy crash mid-week was wrecking her workouts.

The RN ran the wellness assessment, confirmed the Skinny Drip stacked safely on top of her current meds. 45 minutes later, drip done.

Her text the following week, copy-pasted:

*"Wednesday workout didn't fall apart this time. I'm eating the same, taking the same shot, the only thing different was the drip on Sunday. Booking another for next week."*

She kept doing one a week through the rest of her active phase. The energy stopped being the limiter, the workouts stayed in, and her existing plan kept doing its job.

The thing she told me after that stuck. She said she'd been ready to quit GLP-1 because the fatigue was making her miss sessions and skip meals. The drip didn't make her lose anything extra. It made her able to keep doing the thing that was already working.

That's the actual job of the Skinny Drip. It supports the plan you're already running. It doesn't replace it.

Reply "menu" and I'll send the full IV menu if you want to see what we offer alongside the Skinny Drip. Or if you've got a question, send it.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""

# *Subject pattern: story tease. Unnamed composite per IV compliance. No "lost X lbs" claim. Frames drip as adherence support, not weight loss.*


# D5 deadline email — included because Has Deadline=Yes on this offer.
E5_DEADLINE_SUBJECT = "Quick heads up on your intro window, {{contact.first_name}}"
E5_DEADLINE_BODY = """Hi {{contact.first_name}},

Quick heads up. The intro $199 Skinny Drip pricing is a welcome window for new clients and it doesn't sit in your inbox forever.

Here's what's locked in if you book this week:

- $199 Skinny Drip (MIC + B-complex + carnitine + chromium)
- Free pre-drip wellness assessment by a licensed RN
- Mobile setup, RN comes to your home or office within 20 miles of Cincinnati
- 45 minute session

A note on timing. The Skinny Drip lands hardest when you're actively in a weight management phase. If you're between programs or on a maintenance break, it still supports energy and hydration, but the value compounds when you're stacking it on top of an active plan.

Two ways to lock it in:

[Book a Slot]({{custom_values.booking_link}})

Or reply with the day that works best and I'll grab a slot for you directly.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""

# *Subject pattern: deadline + name. Restates offer specifics. Honest "when it works best" qualifier. Two-path CTA.*


E6_SUBJECT = "Remember when I said the Skinny Drip surprises people?"
E6_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing first-time Skinny Drip clients say most often after their session.

Here it is:

*"My workout the next day actually felt like one. I forgot what that was supposed to feel like in a deficit."*

That sentence shows up in our exit feedback almost every week. People expect the drip to do something to the scale. What surprises them is what it does to the work they were already doing, the workout they didn't have to drag themselves through, the meal prep they actually finished, the day they didn't crash at 3pm.

That's the actual mechanism. The Skinny Drip doesn't burn fat for you. It puts your body in a state where the things that DO burn fat (movement, structured eating, sometimes meds) get done consistently. Most weight management plans fail on adherence, not strategy. Energy and hydration are the adherence problem.

I'm not going to push you. If now isn't the right time, that's real. But if you've been telling yourself you'll book it "after the holidays" or "when you've already lost some on your own," that line is the one keeping you exactly where you are.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject pattern: curiosity + permission. Closes Zeigarnik loop from D2. Reframes value as adherence support, not pounds lost.*


E7_SUBJECT = "Why one drip tells you more than reading reviews for a month"
E7_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most people sit on the Skinny Drip decision for weeks. Reading about MIC injections, comparing carnitine doses, wondering if it's worth it on top of everything else they're already paying for in their weight management routine. I get it, the internet makes it easy to research forever and book never.

Here's the part that's worth knowing:

**One Skinny Drip session is the only real test.** Reading about lipotropic blends, B12, chromium, none of that tells you how YOUR body responds, especially during an active deficit. The RN can ballpark it from your wellness check, but the actual answer is one 45-minute session away.

**The intro $199 plus the free wellness assessment is what makes a first session a low-stakes test.** RN comes to you, the assessment confirms the formula fits where you're at right now (and flags if a different drip would land better given your current plan). If after one session you decide it isn't adding to your routine, you've spent less than two months of that supplement subscription you're already running.

**The clients who stick with us almost all say the same thing.** They wish they'd added the drip earlier in their weight management phase. Not because the drip changed their results, because the workouts and the consistency stopped slipping when energy stopped being the limiter.

The intro pricing and the free assessment are still on the table. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""

# *Subject pattern: curiosity + specificity. Logic + cost-of-inaction. Honest framing (drip didn't change results, supported consistency).*


E8_SUBJECT = "Last email from me, plus my direct line"
E8_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

People wait for a reason. The most common ones I hear:

- "I'll book when I'm closer to my goal" (the drip supports the work, doing it earlier in the plan is when it lands hardest)
- "I want to see if I really need it first" (the only way to know is one session, and the wellness assessment is included)
- "I'm not sure if it'll do anything on top of what I'm already doing" (that's literally what the on-site assessment is for, and it's free)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Book directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and pulls up the calendar.

Whatever you decide, thanks for considering us.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""

# *Subject pattern: direct. Phone + KEYWORD as CTA, no button. Permission-to-stop. The screenshot message.*


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your Skinny Drip request, sending the rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick Q so the RN can dial it in, are you on a weight management plan right now (GLP-1, keto, IF, training) or exploring where to start?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent you a welcome email with the rundown. Same question there, are you on a current plan or exploring? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown for first Skinny Drip sessions. Takes 2 min to read. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab a Skinny Drip slot for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, heads up the intro Skinny Drip pricing doesn't sit in your inbox forever. Want me to grab a slot before it lapses?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the Skinny Drip? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text RESET to this number and I'll get the RN on the calendar that week. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your Skinny Drip file or keep it open for whenever you're ready?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the calendar. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the booking link worked. Want me to grab a Skinny Drip slot for you directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on Skinny Drip nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the Skinny Drip Weight Loss IV Therapy nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or rebooked.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from FB form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (current plan vs exploring)
#   D1 10a  E1              welcome + qualifying Q + pratfall up front
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              objections (diet / cadence / vitamin bag) + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (rundown offer)
#   D3 10a  E3              quick-win prep tips
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof (GLP-1 stack story)
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 10a  E5              deadline email (intro pricing window)
#   D5 5p   SMS_D5_5pm      deadline SMS reinforce
#   D7 10a  E6              Zeigarnik close (adherence insight)
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E7              one-session-test + cost of waiting
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E8              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     skinnydrip-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. Skinny Drip — Master Sequence",
        "tag": "skinnydrip-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q Current Plan vs Exploring (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q + Pratfall (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Quick-Win Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 GLP-1 Stack Story Social Proof (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E5 Deadline Intro Pricing Window (D5 10am)", E5_DEADLINE_SUBJECT, E5_DEADLINE_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D5 Deadline SMS Reinforce (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E6 Zeigarnik Close Adherence Insight (D7 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E7 One-Session-Test + Cost of Waiting (D10 10am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E8 Peak-End + RESET Keyword (D14 9am)", E8_SUBJECT, E8_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark Skinny Drip Nurture Complete", ["skinnydrip-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. Skinny Drip — RESET Keyword Recovery",
        "tag": "skinnydrip-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["skinnydrip-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["skinnydrip-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. Skinny Drip — Global Reply Handler",
        "tag": "skinnydrip-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["skinnydrip-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"Skinny Drip Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="Skinny Drip — Weight Loss IV Therapy",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
