#!/usr/bin/env python3
"""
IV Wellness — Afterparty Recovery IV nurture sequence (28-day, linear).

Trigger swaps (set in GHL UI after deploy):
1. WF 01 (Master Sequence) trigger: swap from `afterparty-lead` tag-add to the
   Facebook Lead Ads form for the Afterparty Recovery campaign.
2. WF 02 (RESET Keyword Recovery) trigger: swap from `afterparty-keyword-trigger`
   tag-add to Inbound SMS keyword filter on RESET (any time after D14).
3. WF 03 (Global Reply Handler) trigger: swap from `afterparty-replied` tag-add
   to Customer Replied filtered to WF 01 (so it only fires for active nurture
   contacts, not the whole location).

Generated by `/build-sequence iv-wellness-afterparty-recovery` from offer spec at
Notion page 34f72879-5ff0-8187-b2f0-c543d01c375a.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).

Hard rules (IV strict mode):
- "Supports / helps with / patients often describe" only. Never treats / cures / fixes.
- No before/after photos (no MMS at T+1).
- No em dashes anywhere in body copy.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site RN.
- Real testimonials only or unnamed composites.
- Event-driven psychology: this is an IMPULSE / EVENT-DRIVEN offer. Lead may have
  just attended a wedding, bachelor/ette party, festival, or holiday weekend.
  Nurture pivots to "next time you have an event coming up" rather than long
  therapeutic compounding. No deadline (Has Deadline=No), so urgency comes from
  seasonal/event hooks (Derby, summer wedding season, NYE, holidays).
- Group/event angle: mobile RN to the wedding party hotel suite, the bachelor
  rental, the corporate retreat. That's the differentiator.
- Tone: light, witty, conversational. The category is fun, not somber.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, one quick question before I send you anything"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the Afterparty Recovery IV. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. We do mobile IVs, meaning a licensed RN comes to your hotel room, Airbnb, or home, sets up in about 10 minutes, and you sit (or lie down, no judgment) for the 45 minute push.

One question before I send anything else, because your answer changes what's useful to you:

**Are you exploring this for a current rough morning, or are you planning ahead for an event coming up (wedding, bachelorette, conference, holiday weekend)?**

Reply with "today" or "planning ahead." One word is enough.

In the meantime, here's what your first session looks like:

- Free pre-drip wellness assessment, the RN confirms the Afterparty IV is the right call for you that day
- $175 Afterparty Recovery IV (Zofran anti-nausea, B-vitamins, electrolytes, Toradol)
- Mobile to your hotel, Airbnb, or home within 25 miles of Cincinnati
- Available 7 days a week, including weekends and holidays

Pricing and the full menu are on our site so there are no surprises.

[See Available Times]({{custom_values.booking_link}})

Not ready to book? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""


E2_SUBJECT = "The 3 questions I get most about the Afterparty Recovery IV"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone reaches out about the Afterparty IV. Honest answers below, including the part most places skip.

**1. How fast can you actually come?**
Most weekday mornings we're at your door in 60 to 90 minutes from booking. Weekends in season (wedding months, Derby, holidays) book up fast, so the closer you are to the request the better. If you're planning ahead for a known event, lock the slot the week before.

**2. Do you really come to hotels and Airbnbs?**
Yes. About half our Afterparty bookings are hotel rooms. The RN brings everything, sets up in 10 minutes on a desk or nightstand, and you stay where you are. Front desks rarely care, but if your hotel has a no-medical-services policy we can work around it.

**3. How much does it actually help?**
Patients often describe the nausea lifting in the first 10 to 15 minutes (that's the Zofran). The headache and body ache fade over the next 20 to 30 (Toradol plus rehydration). The full session runs about 45 minutes, and most people say they go from "ruined day" to "functional human" by the time the line comes out.

One honest thing about us. The IV stick is the worst part of the session and we don't pretend otherwise. If you're dehydrated (which, after a heavy night, you are), your veins hide. The RN warms the arm and uses ultrasound if needed. It's a quick poke, but it's not nothing.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing first-time Afterparty IV clients say most often after their session surprised me the first time I heard it. I'll tell you about it in a few days.

{{custom_values.text_message_name}}"""


E3_SUBJECT = "4 things to do alongside any Afterparty IV (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Four small things that make any Afterparty Recovery session work better, true with us or anywhere else.

**1. Book before the event, not the morning after.**
If you know you have a wedding or bachelorette weekend coming, lock the slot in advance. The morning-of slots fill fast, especially Saturdays in summer. Future-you will thank past-you.

**2. Drink water alongside, not instead of.**
The IV pushes about a liter of fluid in 45 minutes, which is great, but your body is still asking for more. Sip water during and after the session. You'll keep the recovery going through the rest of the day.

**3. Eat something bland 30 minutes after.**
The Zofran kicks the nausea, which means food sounds possible again. Toast, banana, plain rice. Keep it simple, no greasy "hangover breakfast" yet, that comes around hour 4.

**4. Skip the second round.**
Most people feel so functional 90 minutes after the IV that they think about going right back to brunch mimosas. The IV restores baseline, it doesn't reset the clock on what you drank. Easy day.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E4_SUBJECT = "The bachelorette suite that ordered four IVs at once"
E4_BODY = """Hi {{contact.first_name}},

True story from last spring. A bride's sister booked us for the bachelorette weekend, four people, all in one Airbnb in OTR. They'd done a brewery tour the day before and a long night out after.

The text I got at 9am Saturday:

*"We are all dying. Please come."*

The RN was there by 10:30. Set up in the living room, four IVs running side by side on the couch and the floor cushions. They watched a movie through it. Maid of honor said it was the only group activity all weekend that everyone actually enjoyed.

The bride messaged me Monday:

*"Hands down the best money we spent the entire weekend. We made the brunch reservation we'd already paid for. Without you we would have slept through it."*

The thing she told me after that stuck. She said the IV wasn't just about feeling better, it saved the day they'd planned. The brunch, the spa appointment, the rehearsal dinner toast they were supposed to write. All of it would have been a write-off otherwise.

Group bookings (3+ people, same address) get a small per-person discount and we bring extra hands for setup. Reply "group" if you want the details for a wedding party, bachelorette, or corporate retreat. Or if you've got a question, send it.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""


E5_SUBJECT = "Remember when I said the Afterparty IV surprises people?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing first-time Afterparty IV clients say most often after their session.

Here it is:

*"I didn't realize how much of my weekend I was writing off."*

That sentence shows up in our exit feedback constantly. People come in expecting to feel a little better, faster. They leave realizing they'd been quietly accepting that one rough day per event was just the cost of going out.

Most of our Afterparty regulars didn't think of themselves as "hangover people." They just had three or four events a year (a wedding, a milestone birthday, a holiday weekend, a conference) where they lost the next day. That added up to almost a full week of "down" days they hadn't been counting.

I'm not going to push you. If now isn't the right time, that's real. But if you've got something coming up (a wedding, a bachelorette, a holiday), the day to plan the recovery is before, not after.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E6_SUBJECT = "Why most people book the second one before the first event"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most people find us in panic mode. Already hungover, already in the middle of a ruined day, frantically searching for "Cincinnati hangover IV." We get it, that's how the category works.

But here's the part that surprises clients:

**About 70% of repeat Afterparty bookings come from people who book the SECOND one before the event, not the morning after.** Once you've felt the difference once, you stop treating recovery as an emergency response and start treating it as part of the event budget. Wedding tickets, hotel, IV. Done.

**The math gets easier when you plan ahead.** Saturday morning slots in season (Derby weekend, June wedding stretch, NYE) book solid. The lead-time slot is calmer for everyone, and you don't have the "is anyone going to show up in time" stress on top of feeling terrible.

**For groups it's even more obvious.** Bachelorette parties, wedding parties, corporate retreats, all of these are easier when the IV is on the calendar before anyone gets there. The maid of honor with the spreadsheet is the one who books us, every time.

That's the actual math. Not "you'll feel like a million bucks" (you'll feel functional, which is the goal). Just "the next time you've got an event you don't want to lose the day after, the booking takes 90 seconds and the relief is on your calendar instead of being a frantic 9am Google search."

The free wellness assessment is still on the table for your first session. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""


E7_SUBJECT = "Last email from me, plus my direct line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

People wait for a reason. The most common ones I hear:

- "I'll book when I actually need it" (you'll be in panic mode and our Saturday slot will be gone)
- "I'm not sure I want to spend $175 on an IV" (compare it to the cost of the weekend you're protecting)
- "I'm not sure mobile IVs are right for me" (that's literally what the on-site assessment is for, and it's free)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Book directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and gets you straight to a slot.

Whatever you decide, thanks for considering us. Have fun out there.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational, light tone.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your Afterparty IV request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you looking for an IV today, or planning ahead for an event coming up?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent you a welcome email with the rundown. Same question there, today or planning ahead? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown for first Afterparty IVs. Takes 2 min to read. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, got an event coming up? Happy to pre-block a slot for the morning after. No charge to hold it."

SMS_D5_5pm = "Hey {{contact.first_name}}, most first-time Afterparty IV clients are surprised by one specific thing. Mind if I share?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the Afterparty IV? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you've got an event coming up, text RESET to this number and I'll lock the morning-after slot. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your Afterparty IV file or keep it open for whenever your next event lands?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the calendar. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the booking link worked. Want me to grab an Afterparty IV slot for you directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on Afterparty Recovery nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the Afterparty Recovery IV nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or rebooked.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from FB form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (today vs planning ahead)
#   D1 10a  E1              welcome + qualifying Q echo
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              objections + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (rundown offer)
#   D3 10a  E3              quick-win prep tips
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof story (group/bachelorette)
#   D4 5p   SMS_D4_5pm      soft slot hold (event-aware)
#   D5 5p   SMS_D5_5pm      curiosity gap
#   D7 10a  E5              Zeigarnik close (writing off the weekend)
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              plan-ahead math + group angle
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     afterparty-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. Afterparty Recovery — Master Sequence",
        "tag": "afterparty-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q Today vs Planning Ahead (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Quick-Win Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Bachelorette Group Story (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Pre-Event Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Writing Off the Weekend (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 Plan-Ahead Math + Group Angle (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + RESET Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark Afterparty Nurture Complete", ["afterparty-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. Afterparty Recovery — RESET Keyword Recovery",
        "tag": "afterparty-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["afterparty-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["afterparty-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. Afterparty Recovery — Global Reply Handler",
        "tag": "afterparty-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["afterparty-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"Afterparty Recovery IV Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="Afterparty Recovery IV — Hangover & Event Recovery",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
