#!/usr/bin/env python3
"""
IV Wellness — Brain Booster IV (Focus & Mental Clarity Drip) nurture sequence.

Trigger model (per `~/.claude/projects/.../project_iv_wellness_nad_workflow_rules.md`):
- WF-01 ships with a tag trigger `brainbooster-lead` because the engine's
  automatic trigger creation only handles `contact_tag` types. The Facebook
  form submission trigger must be swapped in the GHL UI post-deploy
  (the FB form should add the `brainbooster-lead` tag on submit, OR the
  WF-01 trigger should be edited from `Tag Added` to `Facebook Form
  Submission` after the deploy completes).
- WF-02 trigger is the inbound SMS keyword `RESET` (set up in GHL UI).
- WF-03 trigger is `Customer Replied` filtered to `replied to workflow =
  WF-01 Master Sequence` (set up in GHL UI after WF-01 ID is captured).

Generated by `/build-sequence iv-wellness-brain-booster` from offer spec at
Notion page 34f72879-5ff0-8169-bc64-c3c7d79126db.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).
No D5 deadline email because `Has Deadline=No` on this offer.

Hard rules (IV strict mode):
- "Supports / helps with / patients often describe" only. Never treats / cures / fixes.
- No before/after photos (no MMS at T+1).
- No em dashes anywhere in customer-facing SMS or email body strings.
- {{custom_values.text_message_name}} is the bot persona, NOT the on-site RN.
- Real testimonials only or unnamed composites.
- Brain Booster protocol: position around cognitive performance, focus, mental
  clarity. Tee up regular cadence (every 2-3 weeks) in days 10-14 (single
  session shows you it works, the cadence shows you what it actually does).
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "2DvWWl1Ao2MAC9BZVshG"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, one quick question before I send you anything"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the Brain Booster IV. I'm {{custom_values.text_message_name}}, I handle bookings for {{location.name}} here in Cincinnati. We do mobile IVs, meaning a licensed RN comes to your home or office, sets up in about 10 minutes, and you sit comfortably for the 45 minute push.

One question before I send anything else, because your answer changes what's useful to you:

**Are you looking at the Brain Booster for general cognitive performance and biohacking, or is there something specific you're trying to push through (afternoon crashes, brain fog, pressure week at work)?**

Reply with "general" or with the specific concern. One word is enough.

In the meantime, here's what your first session looks like:

- Free pre-drip wellness consult, the RN confirms the Brain Booster is the right call for you that day
- $199 Brain Booster IV (Alpha Lipoic Acid, B-complex, Taurine, NAC)
- Mobile setup, 45 minutes start to finish, you stay at your desk or your couch

Pricing and the full IV menu are on our site so there are no surprises.

[See Available Times]({{custom_values.booking_link}})

Not ready to book? Reply with your biggest question and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}} · {{location.phone}}"""


E2_SUBJECT = "The 3 questions I get most about the Brain Booster"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone reaches out about the Brain Booster. Honest answers below, including the part most places skip.

**1. How is this different from caffeine?**
Caffeine is a stimulant. It blocks the receptor that makes you feel tired, then wears off and the tired comes back harder. The Brain Booster is a different category. Alpha Lipoic Acid, B-complex, Taurine and NAC support the cellular machinery your brain uses to actually produce focus, not borrow it. Patients often describe a clean, steady clarity that lands within a few hours and holds for a couple of days, with none of the crash.

**2. Will I feel it immediately?**
Most clients describe a noticeable lift the same day, often within 2 to 4 hours. By the next morning the focus is sharper and the afternoon dip is dramatically smaller. The full effect compounds across 24 to 48 hours and tapers across 3 to 5 days for most people.

**3. Is it safe for daily demands?**
Your first session includes a full wellness consult by a licensed RN before anything goes in. She reviews your meds, current state, and any past IV history. If anything is a flag, she tells you straight and we don't run the drip. You don't pay for one that isn't a fit. The formula itself is non-stimulant, so you can take it before a presentation morning or before bed without it interfering with sleep.

One honest thing about us. The IV runs cold for the first minute or two, you'll feel a brief cool sensation up your arm, and the B-complex sometimes leaves a faint vitamin taste in the back of your throat for a few seconds. Anyone who tells you it's totally unnoticeable is overselling it. The rest of the session is uneventful.

[See Available Times]({{custom_values.booking_link}})

One more thing. The thing first-time Brain Booster clients say most often after their session surprised me the first time I heard it. I'll tell you about it in a few days.

{{custom_values.text_message_name}}"""


E3_SUBJECT = "4 things to do before any Brain Booster session (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Four small things that make any cognitive IV work better, true with us or anywhere else.

**1. Hydrate hard the day before.**
Aim for 80 to 100 oz of water. The drip runs better when you're already topped off, and the IV stick is easier when your veins are showing up.

**2. Eat a real meal about 60 minutes before.**
Not a protein bar, not just coffee. Empty stomach plus B-complex plus an empty desk is the fastest way to feel a little wired and lightheaded in the first 20 minutes. Real food smooths the whole thing out.

**3. Have your hardest cognitive task queued up for after.**
This one matters. Most people book the Brain Booster as a recovery move, then waste the lift on email. Plan to drop into the deep work block, the strategy doc, the pitch prep, the thing you've been putting off. The clarity is going to land, you might as well aim it.

**4. Skip the pre-drip espresso.**
You're about to feel sharper for hours. You don't need to stack caffeine on top. Most people feel cleaner without it.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E4_SUBJECT = "He booked it once before a Monday board meeting"
E4_BODY = """Hi {{contact.first_name}},

A client reached out last fall. Mid-40s founder, told me he'd been running on five hours of sleep for weeks and had a board meeting Monday morning he could not afford to fumble. He'd tried more coffee. It just made him jittery without making him sharper. He booked one Brain Booster session for Sunday afternoon, said he'd see how it went.

His message Monday night, copy-pasted:

*"Walked in clear. Held the room for two hours and remembered every single follow-up. I'm not sure if I've ever felt that sharp on that little sleep."*

He came back the following Thursday and now does one every two weeks as a default.

The thing he told me after that stuck. He said he'd been treating his brain like it would just keep performing if he kept pushing it, and the reality was it had been running on fumes for months. The Brain Booster didn't make him superhuman. It just gave him back what was already supposed to be there.

That's what most of our cognitive IV regulars describe. Not a high. A return.

Reply "menu" and I'll send the full IV menu if you want to see what we offer alongside the Brain Booster. Or if you've got a question, send it.

[Lock In Your First Session]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""


E5_SUBJECT = "Remember when I said the Brain Booster surprises people?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the thing first-time Brain Booster clients say most often after their session.

Here it is:

*"I forgot what this used to feel like."*

That sentence shows up in our exit feedback about once a week, almost word for word. People walk in expecting a focus boost. They walk out realizing their normal had quietly been a fog for months. The lift isn't dramatic. It's the absence of the static they'd stopped noticing.

Most of our Brain Booster regulars didn't think they had a problem. They thought they were just busy, just tired, just at the age where focus was supposed to slip. One drip later they realized the slip wasn't an age thing, it was a bandwidth thing, and bandwidth is supportable.

I'm not going to push you. If now isn't the right time, that's real. But if you've been telling yourself you'll book it "when this quarter calms down," that line is the one keeping you exactly where you are.

What's the question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""


E6_SUBJECT = "Why the cadence matters more than the first session"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most people treat the Brain Booster like a one-time experiment. Try it once before a big week, see if it lands, decide later. That's a fine way to test the floor of how your brain responds. It is not how the protocol actually works.

Here's the part that surprises clients:

**Cognitive nutrient stores get burned through fast under stress, poor sleep, and high decision load.** A single Brain Booster session refills you noticeably. That window of supported focus and steady energy lasts 3 to 5 days for most people, then it fades, because your demands keep drawing it down.

**A session every 2 to 3 weeks is what compounds.** Each drip puts more of the cofactors back into the system before the previous one has fully tapered. The clarity stops being a "good day" and starts being a baseline. Most clients who run the cadence for 60 days describe it the same way, "I stopped having to push so hard to think."

**A first-timer who books one session and tries to evaluate the protocol from there is grading the wrong test.** The single session shows you it works. The cadence shows you what it actually does to your week.

That's the actual math. Not "you'll feel like a genius." Just "your brain's machinery for focus and recovery gets supported in a way coffee and sleep alone can't reach, and the difference is bigger by week 4 than it is on day 1."

The free wellness consult is still on the table for your first session. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""


E7_SUBJECT = "Last email from me, plus my direct line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

People wait for a reason. The most common ones I hear:

- "I'll book when I'm not so slammed" (you won't be, the calendar doesn't clear)
- "I want to see if I really need it first" (the only way to know is one session, and the wellness consult is included)
- "I'm not sure if it's worth it for the price" (one Brain Booster is $199, one bad afternoon at a board meeting costs more than that, you do the math on which is the better trade)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Book directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our desk, not a queue. You don't fill out a form again, the keyword tells our system who you are and gets you straight to a slot.

Whatever you decide, thanks for considering us.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} from {{location.name}}. Got your Brain Booster request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you looking at the Brain Booster for general performance or for something specific (brain fog, afternoon crash, big week ahead)?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent you a welcome email with the rundown. Same question there, general performance or a specific concern? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick what-to-expect rundown for first Brain Booster sessions. Takes 2 min to read. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab a Brain Booster slot for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, most first-time Brain Booster clients are surprised by one specific thing (and it isn't the focus lift). Mind if I share?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the Brain Booster? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text RESET to this number and I'll get the RN on the calendar that week. {{location.phone}}"

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your Brain Booster file or keep it open for whenever you're ready?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the calendar. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the booking link worked. Want me to grab a Brain Booster slot for you directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on Brain Booster nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the Brain Booster IV nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or rebooked.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from FB form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (general vs specific)
#   D1 10a  E1              welcome + qualifying Q echo
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              objections (caffeine, immediacy, safety) + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (rundown offer)
#   D3 10a  E3              quick-win prep tips
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof story (founder + board meeting)
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 5p   SMS_D5_5pm      curiosity gap (NO deadline email since Has Deadline=No)
#   D7 10a  E5              Zeigarnik close
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              cadence compounding math
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     brainbooster-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. Brain Booster — Master Sequence",
        "tag": "brainbooster-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q General vs Specific (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Quick-Win Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Social Proof Story (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Forgot What This Felt Like (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 Cadence Compounding Math (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + RESET Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark Brain Booster Nurture Complete", ["brainbooster-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. Brain Booster — RESET Keyword Recovery",
        "tag": "brainbooster-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["brainbooster-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["brainbooster-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. Brain Booster — Global Reply Handler",
        "tag": "brainbooster-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["brainbooster-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"Brain Booster IV Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="Brain Booster IV — Focus & Mental Clarity Drip",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
