#!/usr/bin/env python3
"""
TVAAI — Wrinkle Reset Membership (Unlimited Botox/Dysport) nurture sequence.

Trigger swaps to make in the GHL UI before going live:
1. WF 01 trigger: this script seeds tag `wrinklemember-lead`. In the GHL UI swap
   the tag-add trigger for the upstream Facebook Lead Ads form (Funnel Type =
   Lead Form per Notion offer page). The tag stays as the audience filter.
2. WF 02 trigger: swap the tag-add trigger for an inbound SMS keyword filter
   matching `RESET` (case-insensitive) on the location's main number. The
   keyword tag `wrinklemember-keyword-trigger` is the downstream audience
   filter.
3. WF 03 trigger: swap the tag-add trigger for "Customer Replied" filtered to
   contacts who completed WF 01 (i.e. carry the `wrinklemember-lead` tag and
   have not been manually marked resolved).

Generated by `/build-sequence tvaai-wrinkle-reset-membership` from the Notion
offer page at 34f72879-5ff0-813e-b296-c042362d9e8a.

Touchpoint count: 28 across 28 days. Linear only (no parallel sub-workflows).

Hard rules (TVAAI med-spa mode):
- Voice: premium, aesthetic, confident. TVAAI = aesthetics + wellness, Houston.
- "Supports / softens / patients often describe" only. Never treats / cures /
  fixes / freezes / erases / guarantees.
- No before/after photos in SMS (no MMS at T+1).
- No em dashes anywhere in body copy. ` — ` em dash WITH spaces is allowed in
  workflow display names only.
- Zero "100%" anywhere in body copy.
- {{custom_values.text_message_name}} is the bot persona, NOT the injector.
- {{location.name}} / {{location.phone}} / {{location.address}} for clinic info.
- {{custom_values.booking_link}} for the calendar link.
- Tag prefix: `wrinklemember-`
- Has Deadline = No on this offer. NO fabricated urgency, NO "limited slots",
  NO "pricing locked for X weeks". Membership psychology relies on math,
  predictability, and Alle/Aspire reward stacking, not scarcity.
- Subscription discipline: any pricing, billing-cadence, "unlimited" language,
  cancellation terms, included/excluded items must come VERBATIM from the
  Notion offer page or drive reply-to-ask. Do NOT invent unit caps, area
  restrictions, or billing mechanics that Notion is silent on.

Notion-sourced facts used in copy (with source field):
- "$249/mo" -> Price Point + Pricing Research
- "Never pay full price for Botox or Dysport again — unlimited wrinkle
  treatments for one flat monthly rate" -> Core Promise (paraphrased without
  the em dash for body copy)
- "Unlimited Botox or Dysport per month" -> Whats Included
- "Alle + Aspire rewards accrual on all treatments" -> Whats Included + Bonuses
- "priority scheduling" -> Whats Included
- "member discounts on all other services" -> Whats Included
- "No long-term contract — cancel anytime" -> Risk Reversal (rewritten
  comma-form for body copy: "no long-term contract, cancel anytime")
- "Regular Botox users pay $500-800 per visit" -> Why Someone Says Yes
- Three flagged objections (is it really unlimited / what areas are covered /
  is the membership binding) -> Top 3 Objections (handled in E2 by routing
  the area-coverage question to a reply-ask, since Notion does not answer it)
- "Board-certified OBGYN-led practice" -> What Makes Ours Better
- Audience age 28-60, female, $100-200K income, Houston 15-mile radius
  -> Age Range / Gender / Income Level / Geographic Radius

Scaffolding variance from TVAAI sibling (lipbacio) and IV Membership sibling:
- Different opening hook: cost-realization frame ("the math on per-visit Tox")
  instead of lipbacio's softness-vs-overdone qualifier and IV Membership's
  monthly-vs-stretch qualifier.
- Different qualifying split: existing-Botox-user vs. first-time-Tox-curious
  (instead of lipbacio's first-time vs. repeat or IV Membership's monthly vs.
  stretch).
- Different prep-tips email: pre-treatment 48-hour Tox-specific guidance
  (blood-thinner pause, alcohol pause, no workouts post-treatment, no lying
  flat 4 hours post) instead of lipbacio's lip-area prep or IV Membership's
  usage-pattern walkthrough.
- Different social-proof angle: "I stopped tracking how many units I got"
  predictability frame (membership-unique) rather than lipbacio's
  natural-refresh story or IV Membership's decision-fatigue story.
- Different breakup: stays soft, leans on Alle/Aspire reward accrual as the
  "the math keeps working whenever you start" anchor, not on RESET urgency.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.engine import (
    TokenManager, GHLClient, CampaignBuilder,
    sms_step, email_step, wait_step, tag_step, link_steps,
)

LOCATION_ID = "jiR5qR3g4OrMRx6BmpF2"
COMPANY_ID  = "R1HWQKyMMoj4PJ5mAYed"
USER_ID     = "YewkebOufK3hmeP1gx4B"
PARENT_FOLDER = ""

FROM_NAME = "{{custom_values.text_message_name}}"

# ── EMAIL COPY ───────────────────────────────────────────────────────────────

E1_SUBJECT = "{{contact.first_name}}, the per-visit Tox math (and one quick question)"
E1_BODY = """Hi {{contact.first_name}},

Thanks for reaching out about the Wrinkle Reset Membership. I'm {{custom_values.text_message_name}} at {{location.name}}. Most patients who ask about this membership are doing the same quick math in their head, so let me put it on paper before anything else.

Regular Botox or Dysport patients in Houston typically pay $500 to $800 per visit, every 3 to 4 months. The Wrinkle Reset Membership is **$249 a month** for unlimited Botox or Dysport, plus your Alle and Aspire rewards still accrue on every treatment, plus priority scheduling, plus member discounts on every other service we offer. The membership pays for itself in a single visit if you're already a regular.

One quick question before I send you anything else, because your answer changes what's useful to you:

**Are you already a regular Botox or Dysport patient looking for better pricing, or are you newer to neuromodulators and considering your first commitment?**

Reply with "regular" or "new." One word is enough.

While you're thinking, here is what the membership includes, plain text:

- Unlimited Botox or Dysport per month
- Alle and Aspire rewards on every treatment (real money back, $30 to $60 a month in stacked rewards for most members)
- Priority scheduling with the injector
- Member discounts on all our other services (fillers, PDO threads, biostim, IV, peptides, hormone work)
- No long-term contract, cancel anytime

If "unlimited" raises a question for you, send it. I'll answer plainly.

[See Available Times]({{custom_values.booking_link}})

Not ready to enroll? Reply with the question on your mind and I'll answer it personally.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}"""

# *Subject: cost-math frame + question. Different from lipbacio (qualifier-only)
# and IV Membership (one-question-only). Leads with the buying trigger Notion
# flagged: "Savings for regular users." Membership math is visible immediately.*


E2_SUBJECT = "The 3 questions I get most about the Wrinkle Reset Membership"
E2_BODY = """Hi {{contact.first_name}},

Three questions come up almost every time someone asks about the Wrinkle Reset Membership. Honest answers below, including where I'd rather you ask me directly than guess from an email.

**1. Is it really unlimited?**
The membership is built around unlimited Botox or Dysport per month at the $249 monthly rate. There is no per-visit upcharge for the neuromodulator itself inside the membership. If you want a deeper read on exactly how the unlimited structure works in your case (frequency, retreatment timing, what the injector recommends for your face specifically), reply to this email and I'll walk you through it before you enroll. I'd rather you have the full picture than a one-line summary.

**2. What areas are covered?**
This is the one question I always answer one-on-one rather than blanket-emailing, because the honest answer depends on your face and what your goals are. Some patients use the membership for the standard upper-face zones (the ones most people picture when they think "Botox"). Others ask about additional zones our injector handles. Reply with a quick "areas" and I'll send you the exact coverage breakdown for your situation. I won't generalize and risk you booking on a wrong assumption.

**3. Am I locked in long term?**
No. No long-term contract, cancel anytime. We'd rather lose a member who isn't getting value than keep one resentfully. The Alle and Aspire rewards you accrue while you're a member stay yours regardless.

One honest thing about us. We are a board-certified OBGYN-led practice that grew into full-spectrum aesthetics and regenerative wellness, which is unusual in Houston. The flip side is we operate around our injector's calendar, so prime slots fill 5 to 7 days out. Members get priority scheduling, which is the actual reason most of them keep saying it pays for itself.

[See Available Times]({{custom_values.booking_link}})

One more thing. There's a moment members describe around month 2 or 3 that I'll share in a few days. It's the part nobody talks about when they pitch you a Tox membership."""

# *Subject: specificity. Handles all three Notion-flagged objections directly.
# Routes the "what areas" question to reply-to-ask because Notion is silent on
# specific area coverage and we will NOT invent. Zeigarnik teaser closes in
# E5. Pratfall is operational (slots fill). No "100%" anywhere.*


E3_SUBJECT = "5 things to do before any neuromodulator appointment (no sales pitch)"
E3_BODY = """Hi {{contact.first_name}},

No pitch today. Five small things that make any Botox or Dysport appointment go better, true with us or anywhere else.

**1. Skip blood thinners for 48 hours before.**
That includes ibuprofen, aspirin, fish oil, vitamin E, and most pre-workouts. They increase the chance of bruising at the injection sites. Tylenol is fine. If you're on a prescribed blood thinner, do not stop without talking to your prescribing doctor, just let our injector know at your visit.

**2. Skip alcohol for 24 hours before and 24 hours after.**
Alcohol thins your blood and amplifies bruising. The day-of and the day-after are both worth protecting. This is the most-skipped step and the one most likely to cost you a clean result.

**3. Eat a real meal about 60 minutes before.**
A proper meal, not just coffee. Empty stomach plus injections leaves some patients lightheaded.

**4. Plan no workouts and no lying flat for 4 hours after.**
Both increase the risk of the product migrating before it settles into the muscle. After 4 hours you're back to normal, but those first 4 matter. Patients often describe the cleanest results when they treat the rest of the appointment day as a normal-life day, not a hot-yoga or nap day.

**5. Plan a calm 24 hours after.**
You can absolutely return to work, see friends, live your day. But don't book Botox the day before a wedding, big photo, or major event. Onset for most patients is 4 to 7 days, with full effect closer to 14 days. Patients who give themselves a window love their results most.

That's it.

P.S. Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}
{{location.name}}"""

# *Subject: how-to + number. Five Tox-specific items (not lipbacio's lip-area
# four). Pure value, no sell. Replaces lipbacio's lip-area prep and IV
# Membership's usage-pattern walkthrough. P.S. link only. Reciprocity.*


E4_SUBJECT = "She stopped tracking the number"
E4_BODY = """Hi {{contact.first_name}},

A patient enrolled in the Wrinkle Reset Membership last year. Early 40s, regular Botox patient for about six years before joining us, used to get treated every 3 to 4 months at another Houston practice. Her words from a check-in around month 4, paraphrased from the message:

*"I stopped tracking how many units I got last visit. I stopped doing the per-zone calculation in my head while I'm in the chair. I stopped pushing my next appointment back 'just one more week' to stretch the budget. The whole mental tax of being a Botox patient is gone."*

That sentence is what most members describe as the actual product, even though it isn't what we sell.

The visible thing the membership delivers is the cost math. She was paying somewhere between $500 and $800 per visit, three or four times a year. The membership is $249 a month, unlimited, and her Alle and Aspire rewards still accrue on top.

The invisible thing it delivers is the part she described. The mental load of being a regular Botox patient (the budgeting, the spacing, the negotiating with yourself about whether this is the right week) goes away. You stop optimizing it. You just go when your face tells you it's time.

Most of our best members were already regular Botox or Dysport patients before they joined. They had the data point that they liked the results. The membership wasn't a leap of faith, it was a decision to stop running the calculation every visit.

Reply "areas" and I'll send the coverage breakdown for your specific case. Or if you have a different question, send it and it goes straight to me.

[Reserve Your Membership Slot]({{custom_values.booking_link}})

{{custom_values.text_message_name}}"""

# *Subject: story tease. "Stopped tracking" predictability angle is membership-
# unique. Different from lipbacio's natural-refresh story and IV Membership's
# decision-fatigue story (similar mechanism but different emotional shape:
# fatigue is about choosing to come, this is about cost-tracking inside the
# chair). Unnamed composite client. "Reply areas" routes back to E2 unanswered
# question.*


E5_SUBJECT = "Remember when I said members surprise themselves around month 3?"
E5_BODY = """Hi {{contact.first_name}},

A few days back I said I'd share the moment members describe around month 2 or 3 that nobody talks about when they pitch you a Tox membership.

Here it is:

*"My face stopped having a 'good Botox week' and a 'wearing-off week.' It just looks like my face."*

That sentence shows up in our member feedback often enough that I've started paying attention to it. The thing patients don't realize before joining the membership is how much of their experience as a per-visit Botox patient is shaped by the curve. The first 2 weeks after a treatment your face looks one way. The last 3 weeks before your next appointment your face looks another way. Most regular patients are unconsciously aware of which week they're in, even if they wouldn't put it that way.

The membership flattens that curve. Instead of one big infusion every 3 to 4 months, the injector can recommend smaller, better-timed retreatments that keep your face in the same place all year. The Alle and Aspire rewards still accrue. The cost is fixed. The visual result is steadier.

That's the part nobody pitches because it's hard to put on a sales page. You only notice it when it's gone.

I'm not going to push you on this. If now isn't the right season, that's real and the math will still be there whenever you decide. The membership has no long-term contract anyway, so there is no version of this where waiting locks you out of anything.

What's the one question that would actually move the needle for you? Reply, it goes straight to me.

Or whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}}"""

# *Subject: curiosity + permission. Closes Zeigarnik loop from E2. The
# "flatten the curve" angle is membership-unique and substantively different
# from lipbacio's "mirror flinch" close and IV Membership's "days in between"
# close. Honors Has Deadline=No: "the math will still be there whenever you
# decide."*


E6_SUBJECT = "The Alle and Aspire math (the part most people miss)"
E6_BODY = """Hi {{contact.first_name}},

Quick honest one. No sell.

Most patients who consider the membership do the obvious cost math: $249 a month versus $500 to $800 a visit a few times a year. That math already works for regular Botox or Dysport patients. It pays for itself in a single visit if you were going every 3 to 4 months at full per-visit rates.

But the math most people don't run is the rewards stacking. Alle (Allergan's loyalty program for Botox) and Aspire (Galderma's loyalty program for Dysport) both accrue real-dollar rewards on every treatment you receive. Members of the Wrinkle Reset Membership accrue those rewards on every treatment, every month, without paying per visit.

What that means in practice for a steady member:

- Unlimited Botox or Dysport at the $249 monthly rate
- Alle or Aspire reward dollars accumulating on each treatment, often $30 to $60 a month in stacked value back to you
- Priority scheduling, which is its own quiet benefit when the calendar is tight
- Member discounts on everything else we do (fillers, PDO threads, biostim, IV therapy, peptides, hormone work)

Compare that to per-visit Tox at full rates with the same rewards accruing only when you book. The gap widens every month you stay.

I'm not telling you the membership is the right call for everyone. I'm telling you not to say no without running the rewards stacking against your current spend. Plenty of patients enroll once they see the second column.

The membership is no long-term contract, cancel anytime. The Alle and Aspire rewards you earn while you're enrolled stay yours either way.

Whenever you're ready: {{custom_values.booking_link}}

{{custom_values.text_message_name}} · {{location.phone}}"""

# *Subject: curiosity + cost reframe. Membership math is the entire pitch in
# this email. Substantively different from IV Membership's monthly-spend
# reframe (this one centers on Alle/Aspire stacking, which is the
# Notion-flagged differentiator). Has Deadline=No respected: no fake urgency
# anchor. Cancel-anytime keeps the trust frame intact.*


E7_SUBJECT = "Last email from me, plus the front desk line"
E7_BODY = """Hi {{contact.first_name}},

Last email from me on this. I mean it.

Patients delay enrolling for a reason. The most common ones I hear:

- "I want to see if I really need a membership first" (most members were already regular Botox or Dysport patients, the membership just stopped them from doing the math every visit)
- "I'm not sure I'd use it enough to justify it" (the per-visit math at $500 to $800 means you justify it on a single visit you would have already booked)
- "I want to think about the rewards stacking against what I'm already spending" (totally fair, run the numbers, the membership is still here whenever you finish)

If any of those is you, I get it. I'll stop emailing.

Two ways to come back when you're ready:

**1.** Enroll directly: {{custom_values.booking_link}}

**2.** Text **{{location.phone}}** with the keyword **RESET**. Goes to our front desk, not a queue. You don't fill the form out again, the keyword tells our system who you are and gets you straight to the membership setup.

The math will still work the day you decide. The Alle and Aspire rewards still accrue from your first month forward. There is no version of this where waiting penalizes you.

Whatever you decide, thanks for considering us.

{{custom_values.text_message_name}}
{{location.name}}
{{location.address}}
{{location.phone}}"""

# *Subject: direct. Phone + KEYWORD as CTA, no button. Permission-to-stop.
# No urgency anchor, no deadline (Has Deadline=No). Closes with a soft
# "the math still works whenever you decide" anchor that explicitly does
# NOT manufacture scarcity. This is the message people screenshot.*


# ── SMS COPY ─────────────────────────────────────────────────────────────────
# All under 160 chars where possible. No em dashes. Conversational.

SMS_T0 = "Hi {{contact.first_name}}, this is {{custom_values.text_message_name}} at {{location.name}}. Got your Wrinkle Reset Membership request, sending a quick rundown in a sec. Reply STOP to opt out."

SMS_T1 = "Hey {{contact.first_name}}, {{custom_values.text_message_name}} again. Quick question, are you already a regular Botox or Dysport patient looking for better pricing, or newer to it and considering your first commitment?"

SMS_D1_15min = "Hey {{contact.first_name}}, just sent the welcome email with the rundown. Same question there, regular or new to neuromodulators? One word is enough."

SMS_D2_5pm = "Hey {{contact.first_name}}, I put together a quick rundown on what the membership actually includes, including the Alle and Aspire rewards math. Want me to send it?"

SMS_D3_10am = "Is this {{contact.first_name}}?"

SMS_D4_5pm = "Hey {{contact.first_name}}, did you want me to grab a Wrinkle Reset visit for next week, or play it by ear? Either's fine."

SMS_D5_5pm = "Hey {{contact.first_name}}, members usually surprise themselves around month 2 or 3 with one specific thing. Mind if I share what it is?"

SMS_D7_10am = "Hey {{contact.first_name}}, honest one, what's actually holding you back on the membership? No pressure."

SMS_D12_10am = "{{contact.first_name}}, when I don't hear back it's usually timing or a question I haven't answered. Is it one of those?"

SMS_D14_10am = "Last one from me, {{contact.first_name}}. Whenever you're ready, text RESET to {{location.phone}} and I'll get the membership setup queued up. The math still works whenever you start."

SMS_D28_10am = "Hi {{contact.first_name}}, {{custom_values.text_message_name}}. Should I close your Wrinkle Reset Membership inquiry or keep it open for whenever you're ready?"


# ── KEYWORD RECOVERY COPY ────────────────────────────────────────────────────

SMS_RESET_AUTOREPLY = "Got it {{contact.first_name}}, pulling up the membership setup. Here's the link: {{custom_values.booking_link}} -{{custom_values.text_message_name}}"

SMS_RESET_2HR_FOLLOWUP = "Hey {{contact.first_name}}, just making sure the membership link worked. Want me to walk you through enrollment directly?"


# ── REPLY HANDLER COPY ───────────────────────────────────────────────────────

REPLY_ALERT_SUBJECT = "REPLIED LEAD: {{contact.first_name}} on Wrinkle Reset Membership nurture"
REPLY_ALERT_BODY = """REPLIED LEAD ALERT.

{{contact.first_name}} {{contact.last_name}} replied to the Wrinkle Reset Membership nurture sequence.

Phone: {{contact.phone}}
Email: {{contact.email}}

ACTION REQUIRED: Respond within 5 minutes. Do NOT let automation re-engage until this contact is manually marked as resolved or enrolled.

Their last message is in the GHL conversation thread. Check it before replying."""


# ── CAMPAIGN ─────────────────────────────────────────────────────────────────
# Day map for 01-master (cumulative from form submit, 28 automated touchpoints):
#   T+0     SMS_T0          instant confirm + opt-out
#   T+1m    SMS_T1          qualifying Q (regular vs new to neuromodulators)
#   D1 10a  E1              welcome + cost math + qualifying Q + included items
#   D1 10:15a SMS_D1_15min  echo qualifier on SMS channel
#   D2 10a  E2              top 3 membership objections + Zeigarnik teaser
#   D2 5p   SMS_D2_5pm      reciprocity hook (Alle/Aspire rundown offer)
#   D3 10a  E3              5 prep tips for any neuromodulator appointment
#   D3 10a  SMS_D3_10am     pattern interrupt
#   D4 10a  E4              social proof (stopped tracking the number)
#   D4 5p   SMS_D4_5pm      soft slot hold
#   D5 5p   SMS_D5_5pm      curiosity gap (month 2-3 surprise)
#   D7 10a  E5              Zeigarnik close (flattening the Tox curve)
#   D7 10a  SMS_D7_10am     direct question
#   D10 10a E6              Alle/Aspire stacking math
#   D12 10a SMS_D12_10am    objection surfacer
#   D14 9a  E7              peak-end + RESET keyword + phone
#   D14 10a SMS_D14_10am    keyword reminder
#   D28 10a SMS_D28_10am    breakup text
#   tag     wrinklemember-nurture-complete

CAMPAIGN = {
    "01-master": {
        "name": "01. Wrinkle Reset Membership — Master Sequence",
        "tag": "wrinklemember-lead",
        "templates": link_steps([
            sms_step("S0 Instant Confirm + Opt-Out (T+0)", SMS_T0),
            wait_step("1 min", 1, "minutes"),
            sms_step("S1 Qualifying Q Regular vs New (T+1m)", SMS_T1),
            wait_step("22 hours", 22, "hour"),
            email_step("E1 Welcome + Cost Math + Qualifying Q (D1 10am)", E1_SUBJECT, E1_BODY, FROM_NAME),
            wait_step("15 min", 15, "minutes"),
            sms_step("S_D1_15 Echo Qualifier (D1 10:15am)", SMS_D1_15min),
            wait_step("23 hours", 23, "hour"),
            wait_step("45 min", 45, "minutes"),
            email_step("E2 Top 3 Membership Objections + Zeigarnik Teaser (D2 10am)", E2_SUBJECT, E2_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D2 Reciprocity Hook (D2 5pm)", SMS_D2_5pm),
            wait_step("17 hours", 17, "hour"),
            email_step("E3 Pre-Appointment Prep Tips (D3 10am)", E3_SUBJECT, E3_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D3 Pattern Interrupt (D3 10am)", SMS_D3_10am),
            wait_step("24 hours", 24, "hour"),
            email_step("E4 Stopped Tracking The Number Story (D4 10am)", E4_SUBJECT, E4_BODY, FROM_NAME),
            wait_step("7 hours", 7, "hour"),
            sms_step("S_D4 Soft Slot Hold (D4 5pm)", SMS_D4_5pm),
            wait_step("24 hours", 24, "hour"),
            sms_step("S_D5 Curiosity Gap Month 2-3 (D5 5pm)", SMS_D5_5pm),
            wait_step("41 hours", 41, "hour"),
            email_step("E5 Zeigarnik Close Flatten The Curve (D7 10am)", E5_SUBJECT, E5_BODY, FROM_NAME),
            wait_step("1 min", 1, "minutes"),
            sms_step("S_D7 Direct Question (D7 10am)", SMS_D7_10am),
            wait_step("3 days", 3, "days"),
            email_step("E6 Alle Aspire Stacking Math (D10 10am)", E6_SUBJECT, E6_BODY, FROM_NAME),
            wait_step("2 days", 2, "days"),
            sms_step("S_D12 Objection Surfacer (D12 10am)", SMS_D12_10am),
            wait_step("47 hours", 47, "hour"),
            email_step("E7 Peak-End + RESET Keyword (D14 9am)", E7_SUBJECT, E7_BODY, FROM_NAME),
            wait_step("1 hour", 1, "hour"),
            sms_step("S_D14 Keyword Reminder (D14 10am)", SMS_D14_10am),
            wait_step("14 days", 14, "days"),
            sms_step("S_D28 Breakup Text (D28 10am)", SMS_D28_10am),
            tag_step("Mark Wrinkle Reset Membership Nurture Complete", ["wrinklemember-nurture-complete"]),
        ]),
    },

    "02-keyword-recovery": {
        "name": "02. Wrinkle Reset Membership — RESET Keyword Recovery",
        "tag": "wrinklemember-keyword-trigger",
        "templates": link_steps([
            tag_step("Apply Returning Lead Tag", ["wrinklemember-returning-lead"]),
            tag_step("Remove Nurture Complete Tag", ["wrinklemember-nurture-complete"], remove=True),
            sms_step("RESET Auto-Reply with Booking Link", SMS_RESET_AUTOREPLY),
            wait_step("2 hours", 2, "hour"),
            sms_step("RESET 2-Hour Follow-Up", SMS_RESET_2HR_FOLLOWUP),
        ]),
    },

    "03-reply-handler": {
        "name": "03. Wrinkle Reset Membership — Global Reply Handler",
        "tag": "wrinklemember-replied",
        "templates": link_steps([
            tag_step("Confirm Reply Tag Applied", ["wrinklemember-replied"]),
            email_step("Internal Alert to Front Desk", REPLY_ALERT_SUBJECT, REPLY_ALERT_BODY, FROM_NAME),
        ]),
    },
}


# ── RUN ──────────────────────────────────────────────────────────────────────

def main():
    total_steps = sum(len(wf["templates"]) for wf in CAMPAIGN.values())
    print(f"Wrinkle Reset Membership Nurture: {len(CAMPAIGN)} workflow(s), {total_steps} steps\n")

    token_mgr = TokenManager(LOCATION_ID)
    if os.environ.get("GHL_FIREBASE_REFRESH_TOKEN"):
        token_mgr.set_refresh_token(os.environ["GHL_FIREBASE_REFRESH_TOKEN"])

    client = GHLClient(token_mgr, LOCATION_ID)

    print("Testing auth...")
    test = client.request("GET", f"/workflow/{LOCATION_ID}/list?parentId=root&limit=1")
    if not test:
        print("Auth failed! Check your token.")
        sys.exit(1)
    print("Auth OK\n")

    builder = CampaignBuilder(client, LOCATION_ID)
    stats = builder.build(
        CAMPAIGN,
        folder_name="Wrinkle Reset Membership — Unlimited Botox/Dysport",
        parent_folder=PARENT_FOLDER or None,
        company_id=COMPANY_ID,
        user_id=USER_ID,
    )

    if stats["steps_saved"] == total_steps:
        print(f"\nAll {total_steps} steps saved!")
    else:
        print(f"\nWARNING: Expected {total_steps}, saved {stats['steps_saved']}")


if __name__ == "__main__":
    main()
